/*
 ***** ACTIVE SUBDOMAINS
 * ***********************
 *
 * for the moment the following subdomains are active
 * file a pull request to add your own GitHub Page
 *
 *
 **** EXPLANATION
 * ****************
 *
 * KEY:         The subdomain you request (e.g.: "foo" would give the custom domain "foo.js.org" ).
 *
 * VALUE:       The regular domain provided by GitHub (e.g.: "foo.github.io" for a User-/Organisation Page
 *              or "foo.github.io/bar" for a Project Page).
 *
 * IMPORTANT:   To authorise yourself as the owner of the GitHub Page you must have a valid CNAME file
 *              (with the requested domain, e.g: "foo.js.org") to your repository before the pull request.
 *              The requested subdomain must match either your GitHub username or the name of your project
 *              repository. Execeptions are possible for the sake of clarity (e.g. if your project has the
 *              name "foojs" you can request "foo").
 *              Before you start a request for your personal fork of "jquery" or "angular" you should read
 *              the section "naming conflicts" in the wiki!
 *
 * NOTICE:      It would be nice if you could keep the alphabetical order.
 *
 *              Because of the risk of abuse I´m no longer merging requests for pages without content!
 *
 */

var cnames_active = {
    "3bola": "3bola.github.io"
    , "7anshuai": "7anshuai.github.io"
    , "akashacms": "akashacms.github.io"
    , "angularstompdk"; "davinkevin.github.io/AngularStompDK"
    , "algebra": "nicolewhite.github.io/algebra.js"
    , "alt": "goatslacker.github.io/alt"
    , "anenth": "anenth.github.io"
    , "anggao": "anggao.github.io"
    , "annotate": "taitems.github.io/web-pdf-annotation"
    , "annoyingmouse": "annoyingmouse.github.io"
    , "argo": "albertosantini.github.io/argo"
    , "ashabatin": "ashabatin.github.io"
    , "astral": "espinielli.github.io/astraljs"
    , "astrobench": "kupriyanenko.github.io/astrobench"
    , "autodocs": "bguiz.github.io/autodocs"
    , "avi": "avinassh.github.io/avi"
    , "avner": "avnerus.github.io"
    , "awal": "awalGarg.github.io"
    , "badrudeen": "badrudeen.github.io"
    , "begin": "advanced-webapps-class.github.io/begin"
    , "bogdanteodoru": "bogdanteodoru.github.io"
    , "brandonmerritt": "brandonmerritt.github.io"
    , "burst": "hugeen.github.io/burst"
    , "cable": "whatgoodisaroad.github.io/cablejs"
    , "cartodb-demo": "opensas.github.io/cartodb-demo"
    , "chrislaughlin": "chrislaughlin.github.io"
    , "chrismendis": "chrismendis.github.io"
    , "chronos": "espinielli.github.io/chronos"
    , "chy": "chy59.github.io"
    , "clockwork": "arcadiogarcia.github.io/Clockwork.js"
    , "collegequest": "schoolhouserock.github.io/CollegeQuest"
    , "concursos": "mteyss.github.io/concursos"
    , "construyendotrabajo": "mteyss.github.io/construyendotrabajo"
    , "cordova-multiplatform-template": "ckgrafico.github.io/Cordova-Multiplatform-Template"
    , "country": "growmies.github.io/countryjs"
    , "cqrs": "adrai.github.io/cqrs"
    , "crunch": "vukicevic.github.io/crunch"
    , "date": "matthewmueller.github.io/date"
    , "daysfromnow": "pedrokost.github.io/daysfromnow"
    , "dbo": "z3ta.github.io/dbo"
    , "delegacias-fortaleza": "juliosampaio.github.io/delegacias-fortaleza"
    , "dns": "js-org.github.io/dns"
    , "documentation": "documentationjs.github.io",
    , "drag-drop": "clayendisk.github.io/drag-drop.js"
    , "dragonslayer": "kingscott.github.io/dragon-slayer"
    , "elf": "elfjs.github.io"
    , "elliot": "elliotboney.github.io"
    , "emeraldcraftmc": "emeraldcraftmc.github.io"
    , "emulisp": "grahack.github.io/EmuLisp"
    , "euclid": "anandthakker.github.io/euclid"
    , "eventstore": "adrai.github.io/node-eventstore"
    , "festercluck": "festercluck.github.io"
    , "finder": "applait.github.io/finderjs"
    , "flowchart": "adrai.github.io/flowchart.js"
    , "freemarker": "ijse.github.io/freemarker.js"
    , "fromdenisvieira": "fromdenisvieira.github.io"
    , "frzr": "pakastin.github.io/frzr"
    , "geekr": "ruanyl.github.io/geekr"
    , "ghoullier": "ghoullier.github.io"
    , "goodseller": "goodseller.github.io"
    , "graphics2d": "keyten.github.io/Graphics2D"
    , "grapnel": "engineeringmode.github.io/Grapnel.js"
    , "greg": "gregorydgarcia.github.io"
    , "gridsplit": "assetinfo.github.io"
    , "gruft": "nikola.github.io/gruft"
    , "guillotine": "matiasgagliano.github.io/guillotine"
    , "gully": "nmabhinandan.github.io/gully"
    , "gun": "amark.github.io/gun"
    , "happy": "e24.github.io/happy"
    , "hello": "hello-js-org.github.io"
    , "hooloo": "hooloo.github.io"
    , "humanreadable": "matt-sanders.github.io/humanreadable"
    , "hyde": "gheek.github.io/hyde"
    , "iio": "iioinc.github.io/iio.js"
    , "is": "arasatasaygin.github.io/is.js"
    , "ivml": "influencetech.github.io/ivml"
    , "j2p": "j2p.github.io"
    , "jakarta": "jakartajs.github.io/jakartajs"
    , "jakejarrett": "jakejarrett.github.io"
    , "jalbertbowden": "jalbertbowden.github.io"
    , "james": "jamesrowen.github.io/james"
    , "jbone": "kupriyanenko.github.io/jbone"
    , "jjlc": "k-yak.github.io/JJLC"
    , "jodytate": "jodytate.github.io"
    , "json-schema-faker": "pateketrueke.github.io/json-schema-faker"
    , "julien": "julien.github.io"
    , "juno-106": "stevengoldberg.github.io/juno-106"
    , "jvandyke": "jvandyke.github.io"
    , "karl": "karlcoelho.github.io/portfolio"
    , "kingdom": "clayendisk.github.io/kingdom.js"
    , "labelauty": "fntneves.github.io/jquery-labelauty"
    , "laubstein": "laubstein.github.io"
    , "leandro": "leandrowd.github.io"
    , "learnGitBranching": "pcottle.github.io/learnGitBranching"
    , "leipzig": "leipzigjs.github.io"
    , "leon": "leonnardella.github.io/leon"
    , "lightyrs": "lightyrs.github.io"
    , "liguori": "liguori.github.io"
    , "linuxaddict": "linuxaddict.github.io/mario"
    , "logo": "js-org.github.io/logo"
    , "lujaw": "lujaw.github.io"
    , "martin": "martinbutler.github.io"
    , "martingollogly": "martingollogly.github.io"
    , "matthias-schuetz": "matthias-schuetz.github.io"
    , "maxnachlinger": "maxnachlinger.github.io"
    , "maxtracking": "maxtracking.github.io"
    , "medium-header": "danielfeelfine.github.io/medium-header"
    , "mfitzpatrick79": "mfitzpatrick79.github.io"
    , "miguelsr": "miguelsr.github.io"
    , "mikeya": "mikeya.github.io"
    , "mithril": "lhorie.github.io/mithril"
    , "mmcq": "nikola.github.io/MMCQ"
    , "modalizer": "dungo.github.io/modalizer"
    , "mom": "momjs.github.io/mom"
    , "motapc": "motapc97.github.io"
    , "murder": "rolandpoulter.github.io/murder"
    , "mvidalgarcia": "mvidalgarcia.github.io"
    , "ncub8": "ncub8.github.io"
    , "nearley": "hardmath123.github.io/nearley"
    , "nemo": "paypal.github.io/nemo"
    , "newcol": "newcol.github.io"
    , "ng-wig": "stevermeister.github.io/ngWig"
    , "ngn": "nodengn.github.io/NGN"
    , "nikolay": "nikolay.github.io"
    , "notmeirl": "notmeirl.github.io"
    , "nsisodiya": "nsisodiya.github.io"
    , "objectmodel": "sylvainpolletvillard.github.io/ObjectModel"
    , "olimsaidov": "olimsaidov.github.io"
    , "omega": "jczimm.github.io/omega"
    , "on": "clayendisk.github.io/on.js"
    , "opentype": "nodebox.github.io/opentype.js"
    , "opsigor": "opsigor.github.io"
    , "os": "andersevenrud.github.io/OS.js-v2"
    , "paraiba": "paraibajs.github.io"
    , "pathtrace": "kovacsv.github.io/WebGLPathTrace"
    , "paul": "paul-brown.github.io"
    , "pdfutils": "gottox.github.io/node-pdfutils"
    , "pdp-elements": "go4cas.github.io/pdp_elements"
    , "pentris": "justinjc.github.io/pentris2"
    , "pitermarx": "pitermarx.github.io"
    , "pixelart": "meriadec.github.io/PixelartJS"
    , "pliers": "pliersjs.github.io"
    , "polythene": "arthurclemens.github.io/Polythene"
    , "rad": "rapid-application-development-js.github.io/RAD.JS"
    , "radial": "ckgrafico.github.io/radial.js"
    , "rafaelbiten": "rafaelbiten.github.io"
    , "rafaelmangolin": "rafaelMangolin.github.io"
    , "rahul": "rahulsukla.github.io/rahul"
    , "react-autosuggest": "moroshko.github.io/react-autosuggest"
    , "react-shared": "rvikmanis.github.io/react-shared"
    , "relate": "jakelazaroff.github.io/relate"
    , "rp": "rpocklin.github.io"
    , "rwu": "rwu823.github.io"
    , "saturation": "saturation.github.io/www"
    , "saulosantiago": "saulosilva.github.io"
    , "savingthrow": "pdistefano.github.io/SavingThrow.js"
    , "schisma": "schisma.github.io/opensource"
    , "scrolledin": "manuelromeroramos.github.io/scrolledIn.js"
    , "sdk-design": "huei90.github.io/javascript-sdk-design"
    , "sean": "seancallinan.github.io"
    , "select_io": "selaromi.github.io/select_io"
    , "selectric": "lcdsantos.github.io/jQuery-Selectric"
    , "serginator": "serginator.github.io"
    , "shedali": "shedali.github.io"
    , "shorttompkins": "shorttompkins.github.io"
    , "skate": "skatejs.github.io"
    , "skx": "skx.github.io"
    , "sn0w": "greensn0w.github.io"
    , "spectragram,": "adrianengine.github.io/jquery-spectragram"
    , "spin": "fgnass.github.io/spin.js"
    , "spirare": "waldenn.github.io/spirare"
    , "spiritual": "spiritual-js.github.io"
    , "spritesheet": "arcadiogarcia.github.io/Spritesheet.js"
    , "stats": "js-org.github.io"
    , "stepan": "stevermeister.github.io"
    , "stephenmccall": "stephenmccall.github.io"
    , "sugarshin": "sugarshin.github.io/sugarshin.js.org"
    , "sulky": "shingle.github.io/sulky"
    , "supernova": "janbiasi.github.io/supernova"
    , "tagster": "goschevski.github.io/tagster"
    , "tap-flux": "technologyadvice.github.io/tap-flux"
    , "talker": "secondstreet.github.io/talker.js"
    , "temple": "beneaththeink.github.io/Temple"
    , "terminal": "gottox.github.io/terminal.js"
    , "textillate": "jschr.github.io/textillate"
    , "themoviedb": "chrisenytc.github.io/themoviedb"
    , "thundercats": "r3dm.github.io/thundercats"
    , "timerizer": "callumacrae.github.io/timerizerJS"
    , "tint": "tintjs.github.io"
    , "tinylinux": "e8johan.github.io/tiny-js"
    , "ts2jsdoc": "spatools.github.io/ts2jsdoc"
    , "ultcombo": "ultcombo.github.io"
    , "unexpected": "unexpectedjs.github.io"
    , "upresent": "bobbybee.github.io/uPresent"
	, "uvcharts": "imaginea.github.io/uvCharts"
    , "vaguilar": "vaguilar.github.io"
    , "vinimdocarmo": "vinimdocarmo.github.com"
    , "vintesh": "vintesh.github.io"
    , "visualnovel": "selcher.github.io/visualnoveljs"
    , "vncz": "xvincentx.github.io/vncz"
    , "vuongdothanhhuy": "vuongdothanhhuy.github.io"
    , "weaver": "maxkfranz.github.io/weaver"
    , "woodchuck": "ttaylor.github.io/woodchuck"
    , "wwb": "eqielb.github.io/wwb"
    , "xprmntl": "xprmntl.github.io"
    , "xto6": "mohebifar.github.io/xto6"
    , "xtype": "lucono.github.io/xtypejs"
    , "youtim": "mortonfox.github.io/YouTim"
    , "youtube-box": "lucasmonteverde.github.io/youtube-box"
    , "zodiac": "indus.github.io/Zodiac"
    , "zombie": "assaf.github.io/zombie"
}
