/*
 ***** ACTIVE SUBDOMAINS
 * ***********************
 *
 * for the moment the following subdomains are active
 * file a pull request to add your own GitHub Page
 *
 *
 **** README
 * ***********
 *
 * KEY:         The subdomain you request (e.g.: "foo" would give the custom domain "foo.js.org").
 *
 * VALUE:       The regular domain provided by GitHub (e.g.: "foo.github.io" for a User-/Organization Page
 *              or "foo.github.io/bar" for a Project Page).
 *
 * CLOUDFLARE:  JS.ORG uses CloudFlare as its DNS. By default, CloudFlare proxies all requests to your subdomain
 *              to get SSL support (https://foo.js.org) and make use of browser caching with a TTL of 30 min.
 *              But you can opt-out from this and make Cloudflare forward all requests directly to GitHub.
 *              Just add '//noCF' in the line of your requested subdomain to give us a hint.
 *              (all the lines marked with '//noCF?' are from a time when a requester had to explicitly opt-in;
 *              see: https://github.com/js-org/js.org/issues/554)
 *
 * IMPORTANT:   To authorize yourself as the owner of the GitHub Page you must have added a valid CNAME file
 *              (with the requested domain, e.g.: "foo.js.org") to your repository.
 *              The requested subdomain must match either your GitHub username or the name of your project
 *              repository. Exceptions are possible for the sake of clarity (e.g. if your project has the
 *              name "foojs" you can request "foo").
 *              Before you start a request for your personal fork of "react" or "vue" you should read
 *              the section "naming conflicts" in the wiki!
 *
 * NOTICE:      Please follow the format set by everyone else in this file. Entries should use double quotes,
 *              with space between the colon (after the key) and the value and should always be in alphabetical
 *              order. Each line apart from the very last entry should have a comma after it to ensure this file
 *              is valid syntax.
 *
 *              BECAUSE OF THE RISK OF ABUSE, I´M NOT ACCEPTING REQUESTS FOR PAGES WITHOUT REASONABLE CONTENT!
 */

var cnames_active = {
  "": "js-org.github.io",
  "01mz": "01mz.github.io",
  "100dayz": "deadcoder0904.github.io/100dayz",
  "101": "7anshuai.github.io/js101", // noCF? (don´t add this in a new PR)
  "131": "netrvin.github.io",
  "140513": "140513.github.io",
  "1c": "oknosoft.github.io/1c",
  "21cm": "21cm.github.io",
  "23chemistrycamp": "nchuchemistry.github.io/23chemistrycamp",
  "2tube": "you2php.github.io/you2php",
  "360": "360daili.github.io/360daili",
  "3d-go": "3d-go.netlify.com",
  "404": "licshee.github.io/404",
  "766": "766.github.io",
  "7anshuai": "7anshuai.github.io", // noCF? (don´t add this in a new PR)
  "8log": "8log.netlify.app",
  "98": "1j01.github.io/98",
  "9932": "dannyzhan.github.io",
  "a-western-story": "hotsaucefiretruck.github.io/A-Western-Story",
  "a11yslider": "mmahandev.github.io/a11y-slider",
  "a6smile": "a6smile.github.io",
  "aakhilv": "blud3v.github.io/aakhilv",
  "aalaap": "aalaap.github.io",
  "aaron": "57aaron.github.io",
  "abbw": "abbw.github.io",
  "abbyz": "Abbyzhoum.github.io",
  "abc": "afexteam.github.io/abc-mobile",
  "abcdb": "hosting.gitbook.com", // noCF
  "abdalla": "the94air.github.io/abdalla",
  "abelacostaportafolio": "asaa19971a.github.io/AbelAcostaAcostaPortafolio",
  "abhishek": "rpidanny.github.io/personal-collage",
  "abhishekmittal": "abhishek-mittal.github.io/abhishekmittal",
  "abialbon": "abialbon.github.io",
  "aby": "icoldplayer.github.io/aby",
  "acarsy": "acarsy.github.io",
  "accessibility": "guilhermedelemos.github.io/accessibility",
  "accordion": "awps.github.io/Accordion.JS",
  "acebooks": "mohamed0group.github.io/acebooks",
  "acegroup": "mohamed0group.github.io/acegroup",
  "acho": "achojs.github.io/acho",
  "acm": "drew233.github.io/calander",
  "acme": "makepost.github.io/acme-commander",
  "acta": "fabien-h.github.io/acta",
  "action-u": "kevinast.github.io/action-u",
  "active-resource": "nicklandgrebe.github.io/activeresource.js",
  "acyort": "acyortjs.github.io/site",
  "ada": "ada-js.netlify.com",
  "adamant": "datamart.github.io/Adamant",
  "aderemi": "aderemi.github.io",
  "adil": "adilzeshan.github.io/adil",
  "aditya": "aditya81070.github.io",
  "adnanbabakan": "adnanbabakan.github.io",
  "adon988": "adon988.github.io",
  "adv": "advjs.github.io",
  "advancedrpc": "advancedrpc.github.io",
  "aemp": "afexteam.github.io/aemp",
  "aeon": "flazepe.github.io/aeon-web",
  "affiliate": "teamtofu.github.io/affiliate",
  "afmsavage": "afmsavage.github.io",
  "agentnpm": "meetping.github.io/agentnpm",
  "aghasemi": "aghasemi.github.io",
  "agilecards": "otaklapka.github.io/agilecards",
  "agma": "uwynell.github.io/agma.js",
  "agrawalnaman": "agrawalnaman.github.io",
  "agrawalrohit": "rohit0803.github.io/agrawal.github.io",
  "agreytosira": "agreytosira.github.io",
  "ahmad": "aruzikulov.github.io/ahmad",
  "ahmeterdgn": "ahmeterdgn.github.io",
  "ahooks": "ahooks.surge.sh",
  "aider": "tjz101.github.io/aider-js-pages",
  "airtable-plus": "victorhahn.github.io/airtable-plus",
  "ais": "yunyoujun.github.io/ais.js",
  "ajaxable": "artf.github.io/ajaxable",
  "ajinkya": "steelx.github.io/ajinkyaxjs",
  "ajv": "epoberezkin.github.io/ajv",
  "akase": "cedmax.github.io/akase", // noCF? (don´t add this in a new PR)
  "akatsuki": "akatsukijs.github.io/akatsuki",
  "akhyar": "akhyarrh.github.io",
  "aksara": "sajenid.github.io/aksara.js",
  "akshaybhalotia": "akshaybhalotia.github.io",
  "alasql": "alasql.github.io", // noCF? (don´t add this in a new PR)
  "alastor": "aidenybai.github.io/alastor",
  "ale": "alecefe.github.io",
  "alex": "alecs297.github.io",
  "alexanderalvarez": "alexanderalvarez9.github.io",
  "alfred": "amilajack.github.io/alfred",
  "algebra": "nicolewhite.github.io/algebra.js", // noCF? (don´t add this in a new PR)
  "algninja": "algninja.github.io",
  "ali": "alibouhrouche.netlify.com",
  "ali-react-table": "alibaba.github.io/ali-react-table",
  "alien": "pschroen.github.io/alien.js",
  "aligos": "aligos.github.io", // noCF? (don´t add this in a new PR)
  "all": "learnsomuch.github.io/all.js", // noCF? (don´t add this in a new PR)
  "all-contributors": "all-contributors-js-org.netlify.com",
  "almeida": "almeidx.github.io",
  "almin": "almin.github.io",
  "alphabetify": "davidpomerenke.github.io/alphabetify",
  "alt": "goatslacker.github.io/alt", // noCF? (don´t add this in a new PR)
  "alveron": "rofrischmann.github.io/alveron",
  "alyreza": "alyreza.github.io",
  "alys": "rmjordas.github.io/alys",
  "aman": "plug-n-play.github.io/aman",
  "amaple": "amjs-team.github.io/amaple",
  "amine": "am-77.github.io/amine",
  "amorphous": "ariabuckles.github.io/amorphous",
  "ampn": "ampn.github.io",
  "amrit": "amritsrivastava.github.io",
  "ananta": "anantamishra.github.io/ananta",
  "andresito": "andresitodeguzman.github.io/andresito",
  "anenth": "anenth.github.io", // noCF? (don´t add this in a new PR)
  "angular-jsf": "json-schema-faker.github.io/angular-jsf", // noCF? (don´t add this in a new PR)
  "angular-uikit": "whoisjorge.github.io/angular-uikit",
  "angular2in1": "angular2in1.github.io/angular2in1js", // noCF
  "angularstompdk": "davinkevin.github.io/AngularStompDK", // noCF? (don´t add this in a new PR)
  "angumorphism": "bejoistic.github.io/angumorphism-docs",
  "anime": "meguminsama.github.io/anime",
  "animegan": "tonylianlong.github.io/AnimeGAN.js",
  "animo": "thrivingkings.github.io/animo",
  "animorph": "claudiobmgrtnr.github.io/animorph",
  "anna": "anna-wro.github.io/anna",
  "annotate": "taitems.github.io/web-pdf-annotation", // noCF? (don´t add this in a new PR)
  "annoyingmouse": "annoyingmouse.github.io", // noCF? (don´t add this in a new PR)
  "anonymdev": "anonym-anonym.github.io/ANONYM-ANONYM",
  "antalya": "jsantalya.github.io",
  "antropodigital": "antropodigital.github.io/CirculodeEstudio",
  "antwar": "antwarjs.github.io/antwar",
  "anukul": "anukul.github.io",
  "aoang": "aoang.github.io",
  "api-spec": "api-spec.github.io", // noCF? (don´t add this in a new PR)
  "apicluster": "ramsunvtech.github.io/apicluster", // noCF? (don´t add this in a new PR)
  "apilyertia": "apilyertia.github.io",
  "aping": "johnnythetank.github.io/apiNG", // noCF? (don´t add this in a new PR)
  "aplayer": "diygod.github.io/APlayer",
  "apod": "marcosflorencio.github.io/angular-apod", // noCF? (don´t add this in a new PR)
  "applied": "omahajs.github.io/applied",
  "apprun": "yysun.github.io/apprun",
  "appsocket": "appsocket.netlify.com",
  "apr": "ramitos.github.io/apr",
  "aprende-react": "ptcc.github.io/aprende-react",
  "aptrinh": "aptrinh.github.io",
  "arc": "diegohaz.github.io/arc",
  "arcn": "alexakasanjeev.github.io/arcn",
  "arda": "ardasoyturk-portfolio.netlify.app",
  "arga": "cname.vercel-dns.com",
  "argaghulamahmad": "argaghulamahmad.github.io",
  "argo": "albertosantini.github.io/argo", // noCF? (don´t add this in a new PR)
  "ari": "arbo77.github.io/ari",
  "ariang": "p3terx.github.io/ariang", // noCF
  "arief": "1997arief.github.io",
  "arime": "ninbryan.github.io/arime", // noCF? (don´t add this in a new PR)
  "arithmy": "arithmy.netlify.app",
  "arshad": "arshadmhabib.github.io",
  "artalk": "qwqcode.github.io/Artalk",
  "artery": "arteryjs.github.io/gh-pages", // noCF? (don´t add this in a new PR)
  "arthurmbandeira": "arthurmbandeira.github.io",
  "artitalk": "artitalkjs.github.io/docs",
  "asdivyansh": "asdivyansh.github.io",
  "ass": "weizhenye.github.io/ASS",
  "ass-editor": "jeff-tian.github.io/ass",
  "assembly-line": "rubenverg.github.io/assembly-line.js",
  "ast": "kindy.github.io/ast",
  "astral": "espinielli.github.io/astraljs", // noCF? (don´t add this in a new PR)
  "astrobench": "kupriyanenko.github.io/astrobench", // noCF? (don´t add this in a new PR)
  "astx-redux-util": "kevinast.github.io/astx-redux-util",
  "async-af": "asyncaf.github.io/AsyncAF",
  "async-selector-kit": "humflelump.github.io/async-selector-kit",
  "atavic": "atavic.github.io",
  "atenas": "atenasjs.netlify.app",
  "athome": "simon300000.github.io/athome",
  "atombundles": "lirantal.github.io/atombundles",
  "atomgit": "sawyerbx.github.io/atom-git-docs",
  "atomicreact": "atomicreact.github.io/AtomicReact",
  "atx": "aktarytech.github.io/atx",
  "audio-stream": "guywhogeek.github.io/audio-stream",
  "aui": "alauda.github.io/alauda-ui",
  "autarky": "pranshuchittora.github.io/autarky",
  "auto-task-doc": "cname.vercel-dns.com",
  "autodocs": "bguiz.github.io/autodocs", // noCF? (don´t add this in a new PR)
  "automic": "automicjs.github.io",
  "avi": "avinassh.github.io/avi", // noCF? (don´t add this in a new PR)
  "avner": "avnerus.github.io", // noCF? (don´t add this in a new PR)
  "avstream": "akash-joshi.github.io/avstream.js",
  "awesome-alexa": "dolanmiu.github.io/MMM-awesome-alexa",
  "awesome-javascript": "kungfu321.github.io/awesome-javascript",
  "awesome-nuxt": "ansidev.github.io/awesome-nuxt",
  "awesome-vue": "rmjordas.github.io/awesome-vue",
  "awesome-web-react": "dataformsjs.github.io/awesome-web-react",
  "awesomefeed": "arojunior.github.io/awesome-feed",
  "awesomehub": "awesomehub.netlify.com",
  "awesometech10": "awesometech10.github.io",
  "awk": "42ua.github.io/awk",
  "awoo": "awoojs.github.io/website",
  "awto": "alias.zeit.co", // noCF
  "azbuka-vkusa": "bullwinkle.github.io/azbuka-vkusa",
  "azdanov": "azdanov.netlify.com", // noCF
  "aziz": "iaziz786.netlify.com",
  "bachors": "bachors.github.io",
  "backlog": "backlog-js.github.io/backlog.js.org", // noCF? (don´t add this in a new PR)
  "backstage": "backstagejs.github.io/backstage",
  "backwards-n": "backwards-n.github.io",
  "badger": "just-glue-it.github.io/badger", // noCF? (don´t add this in a new PR)
  "badlee": "badlee.github.io",
  "badlydrawnletters": "ql1ke5l98lm5wm0p.preview.edgeapp.net",
  "badlymadebot": "37l9g5rwwrozyeqk.preview.edgeapp.net",
  "badrudeen": "badrudeen.github.io", // noCF? (don´t add this in a new PR)
  "bai": "abaijs.github.io",
  "baicai": "zibaicai.github.io/baicaijsorg",
  "bakhtiyar": "bakszero.github.io",
  "bali": "balijs.github.io",
  "balm": "balmjs.github.io/balm.js.org",
  "bananasplit": "diegoulloao.github.io/bananasplit-js",
  "bancho": "thepoon.github.io/bancho.js",
  "bandicoot": "canopytax.github.io/bandicoot.js.org",
  "bandung": "zufrizalyordan.github.io/bandungjs",
  "baoqi": "baoqi-zhong.github.io",
  "bara": "barajs.github.io/bara",
  "barba": "barbajs.github.io/barba",
  "barbagrigia": "barbagrigia.github.io",
  "base64": "licshee.github.io/base64",
  "bash": "bashjs.github.io",
  "basicgame": "basicgame.github.io/basicGame.js", // noCF? (don´t add this in a new PR)
  "bassdrum": "malte-wessel.github.io/bassdrum",
  "bastion": "snkrsnkampa.github.io/Bastion-Site",
  "batch-cluster": "mceachen.github.io/batch-cluster.js",
  "battle-city": "shinima.github.io/battle-city",
  "battlecry": "battlecry.pedrosm.com",
  "battlerite": "dragory.github.io/battlerite.js",
  "bb26": "ptrkcsk.github.io/BB26",
  "bbn": "jammer99.github.io/bbn",
  "bc": "mazko.github.io/bc.js",
  "bci": "pwstegman.github.io/bcijs",
  "bcklib": "zyyou.github.io/npm-modules",
  "be": "davidep87.github.io/bejs.github.io",
  "beaga": "beagajs.github.io/beaga",
  "becarefulwith": "xMikee1.github.io/becarefulwith",
  "begin": "advanced-webapps-class.github.io/begin", // noCF? (don´t add this in a new PR)
  "benjick": "benjick.github.io",
  "berk": "berkelmas.github.io",
  "bernard": "ojengwa.github.io",
  "berzan": "newbytee.github.io/berzan",
  "besafe": "ma124.github.io/BeSafe",
  "bestof": "michaelrambeau.github.io/bestofjs",
  "besx": "cadox8.github.io/besx",
  "between": "na-west1.surge.sh",
  "bfd": "mrsheldon.github.io/bfd.js",
  "bhadoo-cloud": "ParveenBhadooOfficial.github.io/Bhadoo-Cloud",
  "bigbrainbot": "112batman.github.io/bigbrainbot-website",
  "bind-action-dispatchers": "cchamberlain.github.io/bind-action-dispatchers", // noCF? (don´t add this in a new PR)
  "biu": "aprilorange.github.io/biu", // noCF? (don´t add this in a new PR)
  "black-fury": "black-fury.github.io",
  "blego": "mattstypa.github.io/blego.js.org",
  "blerpy": "Classis21.github.io/blerpy",
  "blessmyrains": "dusterthefirst.github.io/blessmyrains",
  "blockauth": "faragly.github.io/blockauth",
  "blog.arga": "argaghulamahmad.netlify.app", // noCF
  "blog.qbsz": "aboutqbsz.github.io", // noCF
  "blog543": "saepulfariz.github.io/blog543",
  "blogzam": "zam27.github.io/blogzam",
  "blogzen": "mzaini30.github.io/blogzen",
  "bloomer": "algusdark.github.io/bloomer",
  "blotter": "bradley.github.io/Blotter",
  "bloxy": "visualizememe.github.io/bloxy",
  "blu": "aakhilv.github.io/blu",
  "blueconfig": "a-312.github.io/node-blueconfig",
  "bluesky01st": "bluesky01st.github.io",
  "blurple": "blurplejs.github.io/docs",
  "bo": "lfb.github.io/bojs",
  "boats": "discordboats.github.io",
  "bodybuilder": "danpaz.github.io/bodybuilder", // noCF? (don´t add this in a new PR)
  "boiler": "ro0t.github.com/Boiler",
  "boilerplates": "ckgrafico.github.io/frontend-boilerplates",
  "bolao": "ziyou3012.github.io",
  "boldom": "marcisbee.github.io/boldom",
  "bombsweeper": "pakastin.github.io/bombsweeper",
  "bonjour": "danielwetan.github.io/bonjour-web",
  "bonzibuddy": "fardindadev.github.io/bonzibuddy",
  "bookmarklets": "novadevelopment.github.io/bookmarklets.js",
  "bool": "booljs.github.io",
  "booru": "atlasthebot.github.io/booru",
  "booster": "xiaoyang-liu-cs.github.io/booster.js",
  "bootstrap-confirmation": "mistic100.github.io/Bootstrap-Confirmation", // noCF? (don´t add this in a new PR)
  "bootstrap-validate": "pascalebeier.github.io/bootstrap-validate",
  "bootstrap-vue": "alias.zeit.co", // noCF
  "bootstrap-vue-arsenic": "ycs77.github.io/bootstrap-vue-arsenic",
  "bop": "suteki90.github.io/bop",
  "bornaeon": "bornaeon.github.io",
  "botgram": "botgram.github.io/botgram",
  "botlist": "qpgwdz0goem541vo.preview.edgeapp.net",
  "bottender": "yoctol.github.io/bottender",
  "boundless": "enigma-io.github.io/boundless",
  "box": "capacitorset.github.io/box-js", // noCF
  "boxed": "lionking27.github.io/boxed",
  "brain": "brainjs.github.io/brain.js.org",
  "brandifyjs": "greybax.github.io/brandifyjs",
  "brandonmerritt": "brandonmerritt.github.io", // noCF? (don´t add this in a new PR)
  "brasil": "javascriptbrasil.github.io",
  "breadbot": "centralomd.github.io/breadbot",
  "bricklayer": "ademilter.github.io/bricklayer", // noCF? (don´t add this in a new PR)
  "brizusan": "blackmyab.github.io/brizusan",
  "brotat": "mariobob.github.io/brotat-website",
  "browserless": "kikobeats.github.io/browserless",
  "brum": "brumjs.github.io", // noCF? (don´t add this in a new PR)
  "bt": "mldonkey.github.io/bt",
  "btgprice": "beeyev.github.io/btgprice.org",
  "bui": "kjantzer.github.io/bui",
  "bullwinkle": "bullwinkle.github.io",
  "bun": "the94air.github.io/bun",
  "bunjil": "bunjil.netlify.com",
  "bunyan-fork": "cchamberlain.github.io/bunyan-fork", // noCF? (don´t add this in a new PR)
  "bunyan-pmx": "cchamberlain.github.io/bunyan-pmx", // noCF? (don´t add this in a new PR)
  "bunyan-serializer": "cchamberlain.github.io/bunyan-serializer", // noCF? (don´t add this in a new PR)
  "burst": "hugeen.github.io/burst", // noCF? (don´t add this in a new PR)
  "bustime": "agarzola.github.io/bustime", // noCF? (don´t add this in a new PR)
  "butterfly": "cname.vercel-dns.com", // noCF
  "buttermilk": "buttermilk.netlify.com",
  "bwb": "shbwb.github.io/bwb",
  "byakugan": "rockmanvnx6.github.io/byakugan-js",
  "byteasier": "kagurain.github.io/ByteasierIndex",
  "c": "cocobear.github.io",
  "c1200": "c1200.github.io",
  "c-3po": "ttag-org.github.io/c-3po",
  "c-installer": "llenax.github.io/c-installer",
  "cable": "whatgoodisaroad.github.io/cablejs", // noCF? (don´t add this in a new PR)
  "cac": "cac.netlify.com",
  "cachi": "eddiejibson.github.io/cachi",
  "caffeine": "ccrraaiigg.github.io/caffeine",
  "cagatay": "cagataycali.github.io",
  "caissa": "agentx-cgn.github.io/caissa",
  "caizhiyuannn": "caizhiyuannn.github.io",
  "cake-boss": "dannytatom.github.io/cake-boss",
  "calcy": "odevlord.github.io/Calcy", // noCF? (don´t add this in a new PR)
  "calendarios": "helpdev.github.io/Calendarios", // noCF? (don´t add this in a new PR)
  "candy": "candy02058912.github.io/portfolio",
  "candyland": "candyland-js.github.io/candyland",
  "candyref": "bbyjins.github.io/candy",
  "cans": "djyde.github.io/cans", // noCF
  "cantara": "cantarajs.github.io/cantara",
  "canvacord": "snowflake107.github.io/canvacord",
  "canvas": "anshuman-verma.github.io/canvas",
  "canvas-datagrid": "tonygermaneri.github.io/canvas-datagrid",
  "canvasconstructor": "kyranet.github.io/canvas-constructor",
  "canvo": "canvojs.github.io",
  "capital": "capitaljs.github.io/capitaljs",
  "capsid": "capsidjs.github.io/capsid",
  "capsule": "capsule-js-org.github.io/capsule",
  "captcha-canvas": "shashank3736.github.io/captcha-canvas",
  "cardtabs": "blekerfeld.github.io/CardTabs",
  "cargo": "herber.github.io/cargo",
  "carloseduardo": "karllossouza.github.io/carloseduardo.js.org",
  "carmi": "wix-incubator.github.io/carmi",
  "carrot": "kemosaf.github.io/carrot",
  "cartodb-demo": "opensas.github.io/cartodb-demo", // noCF? (don´t add this in a new PR)
  "casl": "stalniy.github.io/casl",
  "cassie": "milesgitgud.github.io/cassie",
  "catbox": "samsamson33.github.io/catbox.js",
  "cats": "whoisjorge.github.io/not-cat-gifs",
  "cbm": "iamnapo.github.io/cbmjs",
  "cdll": "cdll.github.io",
  "cebu": "javascriptcebu.netlify.com",
  "celery-node": "actumn.github.io/celery.node",
  "cenap": "cenapyuce.github.io",
  "cennznet": "cennznet.github.io/cennznet-ui",
  "ceruttimaicon": "ceruttimaicon.github.io",
  "cesaralvarez": "cesaralvrz.github.io/cesaralvarez",
  "cezanne": "hackdoor-io.github.io/cezanne",
  "cgoatone": "cgoatone.github.io",
  "chain-able": "fluents.github.io/chain-able-site",
  "chameleon": "hosting.gitbook.com",
  "chandzhang": "chandzhang.github.io",
  "charge": "charge-js.netlify.com",
  "chariot": "riyacchi.github.io/chariot.js",
  "chatexchange": "jacob-gray.github.io/ChatExchangeJS",
  "checkers": "davidpomerenke.github.io/checkers",
  "cheerio": "cheeriojs.github.io/cheerio",
  "chenyuhu": "chenyuhu.github.io",
  "chenkun": "ck123-rgb.github.io/chenkun-js-org",
  "chernivtsi": "chernivtsijs.github.io",
  "chig": "eliotchignell.github.io",
  "chimon2000": "chimon2000.github.io", // noCF? (don´t add this in a new PR)
  "chirashi": "chirashijs.github.io/chirashi",
  "chitchat": "chitchatjs.github.io",
  "chordthing": "ifons42.github.io/chordthing",
  "chr1stmas": "diegomagdaIeno.github.io/Chr1stmas",
  "chris": "christopher-hayes.github.io/chris",
  "chrismendis": "chrismendis.github.io", // noCF? (don´t add this in a new PR)
  "christo": "christoga.github.io/js-org", // noCF? (don´t add this in a new PR)
  "christopher": "marekkobida.github.io/christopher",
  "chromatography": "teamtofu.github.io/chromatography",
  "chronos": "espinielli.github.io/chronos", // noCF? (don´t add this in a new PR)
  "cineasta": "cineasta-js.github.io/cineasta-docs",
  "ciphercrack": "avirut.github.io/ciphercrack",
  "citation": "citation-js.github.io/site",
  "citeapa": "natsuozawa.github.io/citeapa",
  "city": "city.github.io",
  "civet": "civet-org.github.io",
  "cjss": "cjss-group.github.io/CJSS",
  "ckkibet": "ckkibet.github.io",
  "clabe-validator": "center-key.github.io/clabe-validator",
  "clark": "clarkdo.github.io/new-blog",
  "clarkdo": "clarkdo.github.io",
  "classroom": "epoxydevelopment.github.io/Classroom",
  "clause": "clausejs.github.io/clausejs",
  "cleanblog": "cleanblog.github.io",
  "cleanblog2": "shbwb.github.io/clean-blog-2.0",
  "clearlyelevated": "clearlyelevated.github.io",
  "clevercord": "theanidox.github.io/Clevercord",
  "clockwork": "clockworkdev.github.io/ClockworkWebsite",
  "clusterize": "nexts.github.io/Clusterize.js",
  "cmbhackjs2013": "cmbjs.github.io/cmbHackjs2013",
  "cmdhub": "thatonetqnk.github.io/cmdhub",
  "cml": "didi.github.io/chameleon",
  "cn.history": "doodlewind.github.io/jshistory-cn", // noCF
  "cn.iflow": "unadlib.github.io/iflow-docs-cn",
  "cn.mingyan": "lehs8n.coding-pages.com", //noCF
  "cn.mobx": "sangka.github.io/mobx-docs-cn", // noCF
  "cn.redux": "camsong.github.io/redux-in-chinese", // noCF? (don´t add this in a new PR)
  "cn.rx": "rxjs-cn.github.io/RxJS-Docs-CN", // noCF
  "cnc": "cncjs.github.io/cncjs.org",
  "cndrew": "codemaster233.github.io",
  "codebooky": "hiteshsubnani0128.github.io/codebooky",
  "codemade": "codemade.github.io", // noCF? (don´t add this in a new PR)
  "codepan": "egoist.github.io/codepan",
  "codesurfer": "code-surfer.netlify.com", // noCF
  "codinsky": "izhaki.github.io/codinsky",
  "coffea": "caffeinery.github.io/coffea",
  "coffstation": "coffstation.github.io",
  "coir": "channg.github.io/coir",
  "coldemo": "coldemo.github.io",
  "collect": "collectjs.netlify.com",
  "collegequest": "schoolhouserock.github.io/CollegeQuest", // noCF? (don´t add this in a new PR)
  "colombo": "cmbjs.github.io/CMBJS",
  "color": "akash-joshi.github.io/neural-color-picker",
  "color-ts": "tomas-wrobel.github.io/color-ts",
  "colorise": "mayuraitavadekar.github.io/colorise",
  "colorlab": "signalwerk.github.io/colorlab",
  "colors": "xv700.github.io/colors",
  "comixngn": "seun40.github.io/comix-ngn", // noCF? (don´t add this in a new PR)
  "command": "satoqz.github.io/command.ts",
  "commandfox": "commandfox.github.io/mc-tools", // noCF? (don´t add this in a new PR)
  "commitlint": "conventional-changelog.github.io/commitlint",
  "common-utils-pkg": "iamdevlinph.github.io/common-utils-pkg",
  "community.os": "js.bydiscourse.com", // noCF? (don´t add this in a new PR)
  "compoundinterest": "nategiraudeau.github.io/compound-interest-calculator",
  "concurrent-tasks": "hosting.gitbook.com",
  "concursos": "mteyss.github.io/concursos", // noCF? (don´t add this in a new PR)
  "conductor": "hosting.gitbook.com",
  "conglo": "schwarzkopfb.github.io/conglo",
  "consent": "datamart.github.io/Consent",
  "consono": "r37r0m0d3l.github.io/consono",
  "construyendotrabajo": "mteyss.github.io/construyendotrabajo", // noCF? (don´t add this in a new PR)
  "consultant": "jense5.github.io/consultant",
  "contextify": "abemedia.github.io/jquery-contextify", // noCF? (don´t add this in a new PR)
  "cookiebox": "metaa.gitlab.io/cookiebox.js",
  "cookiecord": "cookiecord.github.io/cookiecord",
  "coolapkwiki": "coolapk-fan.github.io/wiki",
  "coord": "itsacorn.github.io/jscoord",
  "copyer": "tsycode.github.io/copyer.js",
  "copywriting-correct": "rikakomoe.github.io/copywriting-correct",
  "cordclient": "cordclient.github.io/stable",
  "cordova-multiplatform-template": "ckgrafico.github.io/Cordova-Multiplatform-Template", // noCF? (don´t add this in a new PR)
  "coreact": "coreactjs.github.io/coreact",
  "cork": "davej.github.io/CorkJS",
  "corki": "dvtate.github.io/corki",
  "corona": "soroushchehresa.github.io/awesome-coronavirus",
  "corps": "copay.github.io",
  "cosova": "hardo.github.io/cosova",
  "cote": "dashersw.github.io/cote", // noCF? (don´t add this in a new PR)
  "countdown": "igorkowalczyk.github.io/countdown.js",
  "countr": "gleeny.github.io/countr-redirect",
  "country": "growmies.github.io/countryjs", // noCF? (don´t add this in a new PR)
  "cov19": "mixon00.github.io/cov19-cli",
  "cp": "nestedobjects.github.io/cp",
  "cplayer": "copay.github.io/cPlayer",
  "cppkies": "cppkies-team.github.io/Cppkies",
  "cq-websocket": "momocow.github.io/node-cq-websocket",
  "cqrs": "adrai.github.io/cqrs", // noCF? (don´t add this in a new PR)
  "cr": "echosoar.github.io/cr",
  "cracked": "billorcutt.github.io/Cracked",
  "craft": "prevwong.github.io/craft.js",
  "crank": "bikeshaving.github.io/crank",
  "crawlx": "wind2sing.github.io/crawlx",
  "create-next-app": "create-next-app.github.io",
  "create-project": "chalarangelo.github.io/create-js-project",
  "createrest": "atomixinteractions.github.io/createrest",
  "creaturegen": "ryancromebook.github.io/creaturegen",
  "crq": "shbwb.github.io",
  "crunch": "vukicevic.github.io/crunch", // noCF? (don´t add this in a new PR)
  "cryptokey": "rumkin.github.com/crypto-key",
  "crystaldb": "erikmcm.github.io/CrystalDB",
  "csv": "adaltas.github.io/node-csv-docs",
  "cubing": "the-silver-project.github.io/cubing",
  "cucumber-mink": "adezandee.github.io/cucumber-mink", // noCF? (don´t add this in a new PR)
  "cungudafa": "cungudafa.github.io",
  "curi": "pshrmn.github.io/curi",
  "currency": "scurker.github.io/currency.js",
  "curseapp": "mcrocks999.github.io/curseapp.js",
  "customrpc": "realalexsss.github.io/CustomRPC",
  "cville": "CVjs.github.io",
  "cyberflame": "cyberflameu.github.io",
  "cybernaut": "clebert.github.io/cybernaut",
  "cycle": "cyclejs.github.io",
  "cyclow": "pmros.github.io/cyclow", // noCF
  "cyliim": "cyliim.github.io",
  "cyrena": "cyrenajs.github.io/cyrena",
  "cyris": "iCyris.github.io",
  "d-patterns": "alias.zeit.co", // noCF
  "d4": "joelburget.github.io/d4",
  "daily.tmr": "ttttmr.github.io/daily", // noCF
  "dakokonutboi": "dakokonutboi.github.io/portfolio",
  "daksh0225": "daksh0225.github.io",
  "damo": "damodharanj.github.io",
  "damon233": "whatdamon.github.io",
  "dan": "danielh-dev.netlify.com",
  "danmaku": "weizhenye.github.io/Danmaku",
  "danmol": "dan12mol.github.io", // noCF? (don´t add this in a new PR)
  "dap": "jooher.github.io/dap",
  "dapit": "dafitrah.github.io",
  "darkroom": "ajzat34.github.io/darkroom",
  "darshit": "dgupta777.github.io",
  "data-dashboard": "dnajs.github.io/data-dashboard",
  "data-migration": "thebenforce.github.io/data-migration",
  "dataclass": "alexeyraspopov.github.io/dataclass",
  "datastructures": "deadcoder0904.github.io/datastructures",
  "date": "matthewmueller.github.io/date", // noCF? (don´t add this in a new PR)
  "davet": "egecelikci.github.io/davet",
  "dawn": "dawnelixir.github.io/dawn.js.org",
  "dawood": "mohamedawood.github.io/Dawood",
  "day": "dayjs.github.io/website",
  "daybreak": "mokunshao.github.io/daybreak",
  "daysfromnow": "pedrokost.github.io/daysfromnow", // noCF? (don´t add this in a new PR)
  "dbar": "dbarjs.github.io",
  "dbash": "oocydo.github.io/dbash",
  "dblog": "dblog.netlify.com",
  "dbo": "z3ta.github.io/dbo", // noCF? (don´t add this in a new PR)
  "dbothook": "dbots-pkg.github.io/dbothook-website",
  "dbots": "dbots-pkg.github.io",
  "dbt": "aakhilv.github.io/dbt",
  "deck-of-cards": "pakastin.github.io/deck-of-cards",
  "declarativ": "fennifith.github.io/declarativ", // noCF
  "deepcodes": "deepduggal.github.io/deepcodes",
  "deepfractal": "munrocket.github.io/deep-fractal",
  "deepu": "deepu105.github.io",
  "defi": "finom.github.io/defi.js.org",
  "defresh": "hello936.github.io/defresh",
  "delegacias-fortaleza": "juliosampaio.github.io/delegacias-fortaleza", // noCF? (don´t add this in a new PR)
  "delet": "ds-development.github.io/delet",
  "democracy": "invisible-college.github.io/democracy",
  "demoji": "chroventer.github.io/demoji",
  "denalon": "denalon.github.io",
  "denisvieira": "denisvieira05.github.io",
  "deno-tutorial": "hylerrix.github.io/deno-tutorial",
  "deox": "deox.netlify.com",
  "deportes": "andreapins.github.io/Deportes-Gacetis",
  "deputy": "ry4nolson.github.io/Deputy", // noCF? (don´t add this in a new PR)
  "deskn": "dk83l5qmqg6z7q9m.shw.io",
  "detect-resize": "noderaider.github.io/detect-resize", // noCF? (don´t add this in a new PR)
  "detector": "blackmirror1980.github.io/detector-js",
  "deterministic": "nodeguy.github.io/Deterministic.js",
  "developerfolio": "saadpasta.github.io/developerFolio",
  "devsession": "lukasbach.github.io/devsession",
  "dgelong": "alexeyraspopov.github.io/dgelong", // noCF? (don´t add this in a new PR)
  "dhimasanb": "dhimasanb.github.io",
  "dhruvdutt": "dhruvdutt.github.io",
  "diamond": "diamondpkg.github.io/website",
  "dice": "dicediscord.netlify.com",
  "diegomoradev": "edimer-dev.github.io/diegomoradev",
  "diffract": "ameyms.github.io/diffract", // noCF? (don´t add this in a new PR)
  "dinesh": "dineshondev.github.io/dinesh", // noCF? (don´t add this in a new PR)
  "dinos": "0xflotus.github.io/dinos",
  "discodo": "sirubot.github.io/discodo.js",
  "discord": "discordjs.github.io/website",
  "discord-anti-spam": "michael-j-scofield.github.io/discord-anti-spam",
  "discord-bio": "assfugil.github.io/discord.bio",
  "discord-extras": "documentation-html-template.onyx6227.repl.co",
  "discord-giveaways": "androz2091.github.io/discord-giveaways",
  "discord-kr": "discordjs-kr.github.io/website",
  "discord-logs": "androz2091.github.io/discord-logs",
  "discord-player": "androz2091.github.io/discord-player",
  "discord-sensei": "demonicious.github.io/discord-sensei",
  "discord4node": "mrsheldon.github.io/Discord4Node",
  "discordeno": "skillz4killz.github.io/Discordeno",
  "discordhy": "readthedocs.io",
  "discordlib": "hosting.gitbook.com",
  "discordutil": "chroventer.github.io/discordutil",
  "discordutility": "chaosphoe.github.io/discordutility",
  "discunit": "megacode18.github.io/discunit.js",
  "dislink": "relms12345.github.io/Dislink",
  "display": "arguiot.github.io/DisplayJS",
  "distillery": "achannarasappa.github.io/distillery", // noCF? (don´t add this in a new PR)
  "distri": "flarp.github.io/Distri.js",
  "distribution": "distributionjs.github.io/website",
  "districode": "districode.netlify.app",
  "districode-p2p": "districode-p2p.netlify.app",
  "distube": "skick1234.github.io/DisTube",
  "diswrap": "payload-developers.github.io/diswrap.js",
  "div": "div-js.github.io/div.js.org",
  "diysay": "diysay.github.io/diysay-js-org",
  "djsguide": "hosting.gitbook.com",
  "djvu": "russcoder.github.io/djvujs", // noCF
  "djzhao": "djzhao627.github.io",
  "dlite": "hosting.gitbook.com",
  "dm": "bullwinkle.github.io/dm-public",
  "dmitry": "dmitry-zaets.github.io",
  "dna": "dnajs.github.io/dna.js",
  "dns": "js-org.github.io/dns.js.org",
  "docile": "teamtofu.github.io/docile",
  "docs.light": "hosting.gitbook.com", // noCF
  "docsify": "docsifyjs.github.io/docsify",
  "docsify-es": "sidval.github.io/docsify-es",
  "docsify-ru": "truepatch.github.io/docsify-ru",
  "docsite": "txd-team.github.io/docsite-doc-v1",
  "documentation": "documentationjs.github.io", // noCF? (don´t add this in a new PR)
  "docx": "dolanmiu.github.io/docx",
  "dodec-design": "dodec-design.github.io",
  "doggie": "rd73mzg8wwe59yq0.preview.edgeapp.net",
  "dogstack": "dogstack.gitbooks.io/handbook", // noCF
  "dollar": "defims.github.io/dollar",
  "dolphin": "uyouthe.github.io/dolphin",
  "dominion": "dominion-framework.github.io",
  "domtastic": "webpro.github.io/DOMtastic",
  "donavon": "donavon.github.io", // noCF? (don´t add this in a new PR)
  "donut": "kemosaf.github.io/donut",
  "dope": "fouad.github.io/dope", // noCF? (don´t add this in a new PR)
  "dora": "dorakit.github.io/dora.js.org",
  "dot-microservices": "dot-microservices.github.io/dot",
  "dougg0k": "dougg0k.github.io",
  "doz": "dozjs.github.io/website",
  "dplayer": "diygod.github.io/DPlayer", // noCF
  "dpm": "martondev.github.io/dpm",
  "dprof": "andreasmadsen.github.io/dprof",
  "draft": "D1SC0tech.github.io/draft.js", // noCF? (don´t add this in a new PR)
  "drag": "classicoldsong.github.io/Drag.js", // noCF? (don´t add this in a new PR)
  "dragio": "alexkratky.github.io/Dragio.js",
  "dragonman225": "dragonman225.github.io",
  "draw": "skillzzjesse.github.io/draw",
  "dreygur": "dreygur.github.io",
  "drome": "dromejs.github.io/drome.js.org",
  "drupi": "drupijs.github.io/website",
  "dtdevs": "daantje1.github.io",
  "dtools": "mrsheldon.github.io/dtools.js",
  "du": "ruanyl.github.io/du", // noCF? (don´t add this in a new PR)
  "dualcyclone": "dualcyclone.github.io/postit-todo-react-redux",
  "duck": "duckmasteral.github.io",
  "duckfficer": "devtin.github.io/duckfficer",
  "dum": "castmary.github.io/dum.js.org",
  "dumber": "dumberjs.github.io",
  "duncan": "duncann.now.sh",
  "dunedin": "dunedinjs.github.io",
  "dungeon": "youssefelshemi.github.io/dungeon.js",
  "duniter": "duniterspec.github.io",
  "dvan": "dvan.netlify.com",
  "dvd": "cdaringe.github.io/dvd-corner-bounce",
  "dynaflo": "trevorhanus.github.io/dynaflo",
  "dynamic-record": "na-west1.surge.sh",
  "dynamicsnode": "crisfervil.github.io/DynamicsNode",
  "dynwriter": "orbitalproject.github.io/dyn-client",
  "dyo": "dyo.github.io/dyo",
  "eahmed234": "eahmed234.github.io",
  "ease": "chisel.github.io/ease",
  "easy-bot": "bigaston.github.io/easy-bot",
  "easybuy": "danielwetan.github.io/easybuy",
  "easyht": "yellowface233.github.io/easyht-website",
  "eatery-nod-w": "kevinast.github.io/eatery-nod-w",
  "ebnsina": "ebnsina.github.io/js.ebnsina.me",
  "echo": "licshee.github.io/echo.js",
  "eco": "snowflake107.github.io/quick.eco",
  "ecstar": "mouse484.github.io/Ecstar",
  "ed2k": "sunnyli.github.io/ed2k.js",
  "edazpotato": "edazpotato.github.io",
  "ef": "classicoldsong.github.io/ef.js.org",
  "efemerides": "andreapins.github.io/Efemerides",
  "effectful": "awto.github.io/effectfuljs",
  "effects": "effectsjs.github.io/effectsjs",
  "eggsy": "eggsywashere.github.io",
  "ehsan": "ehsanfox.github.io",
  "eiphop": "eiphop.netlify.com",
  "ejir": "ejir.github.io",
  "elastic-builder": "sudo-suhas.github.io/elastic-builder",
  "elasticmagic": "kindritskyimax.github.io/elasticmagic-js",
  "electron-react-boilerplate": "electron-react-boilerplate.github.io/site",
  "electron-settings": "nathanbuchar.github.io/electron-settings",
  "elementnet": "elementnet.github.io",
  "eleven": "elevendev.github.io",
  "elf": "mytharcher.github.io/elf.js.org", // noCF? (don´t add this in a new PR)
  "elixor": "hosting.gitbook.com",
  "eliza": "chigix.github.io/eliza-instrumentality",
  "elliot": "elliotboney.github.io", // noCF? (don´t add this in a new PR)
  "elmo": "lap00zza.github.io/elmo",
  "elock": "yourtion.github.io/node-elock",
  "emage": "douglasjunior.github.io/emage",
  "email-templates": "niftylettuce.github.io/email-templates",
  "embarrassed-themes": "kbothub.github.io/Embarrassed-Themes",
  "embedlam": "wnda.github.io/embedlam",
  "ember-cli-page-object": "san650.github.io/ember-cli-page-object", // noCF? (don´t add this in a new PR)
  "ember-electron": "adopted-ember-addons.github.io/ember-electron",
  "emeraldcraftmc": "emeraldcraftmc.github.io", // noCF? (don´t add this in a new PR)
  "emoji": "egoist.github.io/emoji",
  "emoji-button": "joeattardi.github.io/emoji-button",
  "emojifier": "badlydrawnletters.github.io/emojifier-docs",
  "emojipanel": "danbovey.github.io/EmojiPanel",
  "empathy": "the94air.github.io/empathy-docs",
  "emre": "emrekara37.github.io",
  "emulisp": "grahack.github.io/EmuLisp", // noCF? (don´t add this in a new PR)
  "emxi": "emxi.github.io",
  "enclave": "eanplatter.github.io/enclave", // noCF? (don´t add this in a new PR)
  "endb": "chroventer.github.io/endb",
  "endersquid": "endersquidjs.github.io",
  "endpoint-imposter": "lukaszmakuch.github.io/endpoint-imposter",
  "energy": "energychain.github.io/energy",
  "engui": "engui.github.io",
  "eon": "eon-web.github.io/eon",
  "eplayer": "132yse.github.io/eplayer",
  "epoxy": "hosting.gitbook.com",
  "eq8": "eq8.github.io",
  "eqeq": "slikts.github.io/js-equality-game",
  "eray": "erayarslan.github.io", // noCF? (don´t add this in a new PR)
  "erdems": "erdemsweb.github.io",
  "erebos": "mainframehq.github.io/erebos",
  "eren": "eren885.github.io",
  "erest": "yourtion.github.io/node-erest",
  "erik": "erikroyall.github.com", // noCF? (don´t add this in a new PR)
  "erikng": "eriknguyen.github.io",
  "ero": "mst-2.github.io/ero",
  "erpeel": "fikriks.github.io/erpeel",
  "es-interview": "hylerrix.github.io/es-interview",
  "es.redux": "sergiodxa.github.io/redux-in-spanish", // noCF? (don´t add this in a new PR)
  "es.single-spa": "single-spa.github.io/es.single-spa.js.org", // noCF
  "es2015-node": "martinheidegger.github.io/es6modules-nodejs", // noCF? (don´t add this in a new PR)
  "es6-module-seed": "blackmirror1980.github.io/es6-module-seed",
  "es6-tween": "tweenjs.github.io/es6-tween",
  "escape": "licshee.github.io/Escape.js", // noCF? (don´t add this in a new PR)
  "esfx": "esfx.github.io",
  "esg": "faystart.github.io/ESG",
  "esper": "codecombat.github.io/esper.js",
  "estudiantil": "milersant.github.io/estudiantil",
  "eta": "alias.zeit.co", // noCF
  "eth": "eth-js.github.io/eth-dev-tools",
  "ethaan": "ethaan.github.io/webpage",
  "ethavatar": "filips123.github.io/EthAvatar.JS",
  "euc": "wnda.github.io/euc",
  "euclid": "anandthakker.github.io/euclid", // noCF? (don´t add this in a new PR)
  "eval": "jshawl.github.io/eval", // noCF? (don´t add this in a new PR)
  "event-storage": "albe.github.io/node-event-storage",
  "eventstore": "adrai.github.io/node-eventstore", // noCF? (don´t add this in a new PR)
  "everything": "ajays97.github.io/Everything.js",
  "evolutionland": "evolutionlandorg.github.io/js-sdk",
  "evolutions": "anshumanv.github.io/evolutions-webapp",
  "evolve": "evolvejs.github.io",
  "ewa": "lyfeyaj.github.io/ewa",
  "exbars": "youssefkababe.github.io/exbars", // noCF? (don´t add this in a new PR)
  "excmd": "elliottcable.github.io/excmd.js",
  "exeform": "hosting.gitbook.com", // noCF
  "exiftool-vendored": "mceachen.github.io/exiftool-vendored.js",
  "exp": "magicops.github.io/JQuery-expression-builder",
  "expressad": "flweber.github.io/express-ad-basicauth",
  "expressdynamichelpers": "marvnet.github.io/express-dynamic-helpers-patch",
  "extenso": "theuves.github.io/extenso.js.org",
  "extraction": "rse.github.io/extraction", // noCF? (don´t add this in a new PR)
  "eye": "arguiot.github.io/EyeJS",
  "faceapp": "negarang.github.io/face-app",
  "facepalm": "santiagogil.github.io/facepalm",
  "facreative": "facreative.github.io",
  "fairy": "fairymeee.github.io",
  "fallr": "faisalman.github.io/fallr-js",
  "fan": "garychamberlain.github.io/fan",
  "fantas": "fantastiser.github.io",
  "farfetchd": "achannarasappa.github.io/farfetchd", // noCF? (don´t add this in a new PR)
  "farzad": "wikiweb.github.io/farzad",
  "faux": "fauxOS.github.io",
  "fcbosque": "cronopio.github.io/fcbosque", // noCF? (don´t add this in a new PR)
  "fe": "xcss.github.io/FE",
  "feature-u": "kevinast.github.io/feature-u",
  "feeble": "feeblejs.github.io/feeble",
  "feedback": "mubaidr.github.io/feedback.io",
  "fela": "rofrischmann.github.io/fela", // noCF? (don´t add this in a new PR)
  "fem": "frani.github.io/fem",
  "festercluck": "festercluck.github.io", // noCF? (don´t add this in a new PR)
  "fetch-json": "center-key.github.io/fetch-json",
  "fidel": "fidelxyz.github.io",
  "fikri": "ikrydev.github.io/fikri.js.org",
  "filer": "filerjs.github.io/filer",
  "finder": "applait.github.io/finderjs", // noCF? (don´t add this in a new PR)
  "fini": "janovekj.github.io/fini",
  "fire-hydrant": "cchamberlain.github.io/fire-hydrant", // noCF? (don´t add this in a new PR)
  "fireblast": "thefireblast.github.io",
  "firenze": "fahad19.github.io/firenze", // noCF? (don´t add this in a new PR)
  "fireorm": "wovalle.github.io/fireorm",
  "five": "jackdcrawford.github.io/five",
  "flamecord": "flamexode.github.io/flamecord",
  "flameshot": "flameshot-org.github.io",
  "flap": "slurmulon.github.io/flap",
  "flash": "flashcardjs.github.io",
  "flatpickr": "flatpickr.github.io",
  "flavor": "blackmirror1980.github.io/flavor-js",
  "fld-grd": "mrksbnch.github.io/fld-grd",
  "flexmasonry": "kavanmevada.github.io/flex_masonry", // noCF
  "flood": "flood.jesec.io", // noCF
  "flot": "flottant.github.io",
  "flowchart": "adrai.github.io/flowchart.js", // noCF? (don´t add this in a new PR)
  "flowcon": "oknosoft.github.io/flowcon",
  "flowpainter": "sirajchokshi.github.io/FlowPainter",
  "fluid": "jottocraft.github.io/fluid",
  "fluorite": "chisel.github.io/fluorite",
  "fluxoff": "kingscott.github.io/flux-off", // noCF? (don´t add this in a new PR)
  "flvplayer": "zhw2590582.github.io/FlvPlayer",
  "flybook": "rhiokim.github.io/flybook",
  "flying-squid.prismarine": "prismarinejs.github.io/flying-squid",
  "flysoft": "minecraftsky.github.io",
  "fmateoc": "fmateoc.github.io",
  "fmkli": "fmkli.github.io",
  "fnbr": "fnbrjs.github.io/docs",
  "fnx": "fnxjs.gitbooks.io/fnx-documentation",
  "focusoverlay": "mmahandev.github.io/FocusOverlay",
  "fontdragr": "ryanseddon.github.io/font-dragr",
  "food": "teamtofu.github.io/foodweb",
  "forceify": "dalisoft.github.io/Forceify",
  "form": "the94air.github.io/form",
  "formred": "zewish.github.io/formred",
  "formvuelate": "formvuelate.netlify.app",
  "fortnite": "ickerio.github.io/fortnite.js",
  "fortune": "fortunejs.github.io/fortune", // noCF? (don´t add this in a new PR)
  "fosspwa": "foss-pwa.github.io/app-store",
  "foxford": "netology-group.github.io/foxford.github.io",
  "foxify": "foxifyjs.github.io/foxify",
  "foxman": "kaola-fed.github.io/foxman",
  "frame-depth": "nwong212.github.io/frame-wizard",
  "framework": "plasnerd.github.io/Framework.js",
  "frameworkless": "mtimofiiv.github.io/frameworkless",
  "frankmosca": "alias.zeit.co", // noCF
  "fre": "132yse.github.io/fre",
  "freemarker": "ijse.github.io/freemarker.js", // noCF? (don´t add this in a new PR)
  "freezer": "pakastin.github.io/freezer",
  "frint": "frintjs.github.io/frint.js.org",
  "fritzbox": "lesander.github.io/fritzbox.js",
  "front-end": "whoisjorge.github.io/front-end",
  "frontless": "nesterow.github.io/frontless",
  "frzr": "pakastin.github.io/frzr",
  "fs-nextra": "bdistin.github.io/fs-nextra",
  "fte": "scintilla4evr.github.io/fte",
  "fucao": "fusuhub.github.io",
  "fuck": "gerd2002.github.io/fuck.js",
  "fullscreen": "motyar.github.io/fullscreen",
  "funbook": "egoist.github.io/funbook",
  "funbot": "jch-notprogram.github.io/funbot-website",
  "fusilli": "anthemaker.github.io/Fusilli.js",
  "futch": "jfbrennan.github.io/futch",
  "fyi": "tobihrbr.github.io/fyi",
  "g": "nodebox.github.io/g.js",
  "gal": "galmail.github.io", // noCF? (don´t add this in a new PR)
  "game-tracker": "endbug.github.io/game-tracker",
  "gamedevcontestal": "fromdenisvieira.github.io/gamedevcontestal", // noCF? (don´t add this in a new PR)
  "gametracker": "officialpiyush.github.io/gametracker.js",
  "gamingnet": "gamingmineblox.github.io/GamingNet",
  "gatsby-source-pixiv": "poipoii.github.io/gatsby-source-pixiv",
  "gazosekai": "starkblaze01.github.io/Gazo_Sekai",
  "gcse": "abemedia.github.io/jquery-gcse",
  "gdi": "ParveenBhadooOfficial.github.io/Google-Drive-Index",
  "geekr": "ruanyl.github.io/geekr", // noCF? (don´t add this in a new PR)
  "geniucker": "geniucker.github.io",
  "genpasswd": "exos.github.io/genpasswd", // noCF? (don´t add this in a new PR)
  "geolocation-promise": "js-pugilist.github.io/geolocation-promise",
  "george": "georgeyue.github.io/george",
  "gerardo": "gvzq.github.io/gerardo",
  "german": "dipanshkhandelwal.github.io/Learning-German",
  "germanov": "germanov-dev.github.io",
  "get": "hxco.github.io/Get",
  "getdot": "enderandfiredev.github.io/getdot",
  "getlink": "ilovecode1.github.io/linkjs", // noCF? (don´t add this in a new PR)
  "ghapi": "haydennyyy.github.io/node-ghapi",
  "ghastly": "hkwu.github.io/ghastly",
  "ghsamm": "ghsamm.github.io", // noCF? (don´t add this in a new PR)
  "giant-piano": "moroshko.github.io/giant-piano", // noCF? (don´t add this in a new PR)
  "girish": "chaudhs769.github.io/girish.js.org",
  "girls": "girls-js.github.io",
  "girlscript": "girlscriptjaipur.github.io",
  "gitdown": "gc.github.io/gitdown",
  "gitinit": "silly-shirley-8e44e3.netlify.com",
  "gitm": "gitm.netlify.com",
  "gitme": "gitme.netlify.com",
  "gitmoji": "jeff-tian.github.io/gitmoji",
  "gitstyle": "inKerk.github.io/git-style-guide",
  "gka": "gkajs.github.io/gka",
  "glaze": "kripod.github.io/glaze",
  "glitterbot": "glitterbot.netlify.com", // noCF
  "glize": "datamart.github.io/Glize",
  "glottologist": "arguiot.github.io/Glottologist",
  "gnatale": "giosooul.github.io/gnatale.github.io",
  "god": "godow.github.io",
  "godzm4tt3o": "godzm4tt3o.github.io",
  "gogs": "rpgjw54g31k5yd4q.preview.edgeapp.net",
  "goji": "airbnb.github.io/goji-js",
  "gol": "goljs.github.io/GoL",
  "gondel": "namics.github.io/gondel",
  "good": "amirhossein693.github.io/good",
  "goodshare": "koddr.github.io/goodshare.js",
  "gotanda": "gotandajs.github.io",
  "gottasurf": "jottocraft.github.io/surf",
  "graffy": "aravindet.github.io/graffy",
  "gram": "gram-js.github.io/gramjs",
  "gramps": "gramps-graphql.github.io/gramps",
  "graph": "tomas-wrobel.github.io/graph",
  "graphene": "graphene-react.netlify.com",
  "graphics2d": "keyten.github.io/Graphics2D", // noCF? (don´t add this in a new PR)
  "graphstore": "besync.github.io/graphstore",
  "grapnel": "engineeringmode.github.io/Grapnel.js", // noCF? (don´t add this in a new PR)
  "gregory": "f3z0.github.io",
  "grep": "42ua.github.io/grep",
  "greylock": "datamart.github.io/Greylock",
  "gridiron": "noderaider.github.io/gridiron",
  "gridsplit": "assetinfo.github.io", // noCF? (don´t add this in a new PR)
  "grub": "grubburg.github.io/blog",
  "gruft": "nikola.github.io/gruft", // noCF? (don´t add this in a new PR)
  "grumpy": "aidenybai.github.io/grumpy",
  "gtfs": "gtfs-js.github.io/gtfs.js.org",
  "guguji5": "guguji5.github.io",
  "guilherme": "guilhermedelemos.github.io/guilherme",
  "guillotine": "matiasgagliano.github.io/guillotine", // noCF? (don´t add this in a new PR)
  "guineapigbot": "guineapigbot.github.io",
  "guiseek": "guiseek.github.io", // noCF? (don´t add this in a new PR)
  "gully": "nmabhinandan.github.io/gully", // noCF? (don´t add this in a new PR)
  "gulpkit": "gulpkit.github.io/GulpKit",
  "gun": "gundb.github.io", // noCF? (don´t add this in a new PR)
  "guppy": "daniel3735928559.github.io/guppy",
  "guuibayer": "guuibayer.github.io", // noCF? (don´t add this in a new PR)
  "gylidian": "gylidian.github.io",
  "gyps": "huijari.github.io/Gyps",
  "gyre": "wridder.github.io/GyreJS", // noCF? (don´t add this in a new PR)
  "gyx": "yourtion.github.io/gyx.js.org",
  "h": "makenowjust.github.io/h.js",
  "h3": "h3rald.github.io/h3",
  "h7ml": "h7ml.github.io/web",
  "ha-store": "fed135.github.io/ha-store",
  "habra": "jarvis394.github.io/habra",
  "hacktm": "hacktm.netlify.com",
  "hahuutin": "hahuutin.github.io",
  "hale": "haleshaw.github.io/hale",
  "halil": "hibrahimsafak.github.io", // noCF? (don´t add this in a new PR)
  "haloapi": "derflatulator.github.io/haloapi.js", // noCF? (don´t add this in a new PR)
  "ham": "militia21.github.io/ham",
  "hamburger-menu": "center-key.github.io/hamburger-menu",
  "hamed": "phpniki.github.io/hamed",
  "hanan": "hanandito.github.io/teddypicker",
  "handsfree": "handsfreejs.github.io/handsfree",
  "hapi-sol": "yonjah.github.io/hapi-sol",
  "happy": "e24.github.io/happy", // noCF? (don´t add this in a new PR)
  "happyae": "happyae.github.io",
  "hay": "hayjs.github.io/hay.js.org",
  "hbase": "adaltas.github.io/node-hbase-docs",
  "heartseekers": "rajington.github.io/heartseekers", // noCF? (don´t add this in a new PR)
  "hegel": "jsmonk.github.io/hegel",
  "hello": "hello-js-org.github.io", // noCF? (don´t add this in a new PR)
  "helper": "tbnritzdoge.github.io/helperweb",
  "hfsyun": "hfsyun.github.io",
  "hibiki": "claritymoe.github.io/hibiki",
  "hickacou": "hickacou.github.io",
  "highway": "dogstudio.github.io/highway",
  "hijiangtao": "hijiangtao.github.io/hijiangtao.js.org",
  "hilo": "erikroyall.github.io/hilo", // noCF? (don´t add this in a new PR)
  "hilo3d": "hiloteam.github.io/Hilo3d",
  "hiteshsubnani": "hiteshsubnani0128.github.io/hiteshsubnani",
  "hiven": "hivenapp.github.io/hiven.js",
  "hk": "akura-co.github.io/hk", // noCF? (don´t add this in a new PR)
  "hltvbot": "nescabir.github.io/HLTVBot",
  "hoa": "thehoa.github.io",
  "hoast": "hoast.github.io",
  "hois": "hoisW.github.io",
  "holidaycss": "evgenyorekhov.github.io/holiday.css",
  "hooked-on-redux": "harryhope.github.io/hooked-on-redux",
  "hookstate": "hookstate.netlify.com", // noCF
  "hooloo": "hooloo.github.io", // noCF? (don´t add this in a new PR)
  "how-to-mithril": "stephanhoyer.github.io/how-to-mithril",
  "hrishi": "hrishi045.github.io",
  "hrtable": "uyouthe.github.io/hrtable",
  "hsiaoyi0504": "hsiaoyi0504.github.io",
  "htmljar": "syntacstudio.github.io/html-jar",
  "htony": "themetony.github.io/hugo-theme-tony",
  "http4ts": "http4ts.github.io/http4ts",
  "httpunit": "samzh72.github.io/httpunit",
  "hub": "yyued.github.io/hub.js",
  "hubble": "hubble.netlify.com",
  "hugorocaproyectos": "hugoroca.github.io/coleccion-proyectos",
  "human": "human-js.gitbooks.io", // noCF? (don´t add this in a new PR)
  "humble": "humblejs.github.io",
  "hx": "hx-js-org.d53923.flexbalancer.net",
  "hybrids": "hybridsjs.github.io/hybrids",
  "hyde": "gheek.github.io/hyde", // noCF? (don´t add this in a new PR)
  "hydro": "hydro-dev.github.io",
  "hydrogen": "siddharthbose-codeware.github.io/hydrogen-website",
  "hyf": "yafey.github.io",
  "hyperform": "hyperform.github.io",
  "hyperhtml-styleguide": "albertosantini.github.io/hyperhtml-styleguide", // noCF
  "i18n4v": "shibukawa.github.io/i18n4v",
  "iagrib": "iagrib.github.io",
  "iamsurajdc": "iamsurajdc.github.io",
  "icecast": "jucrouzet.github.io/icecast.js",
  "ices": "icesjs.github.io/ices",
  "icones": "icones.netlify.app",
  "id": "andae.github.io/id",
  "id3": "jeff-tian.github.io/id3",
  "idettman": "idettman.github.io",
  "ienumerable": "mbasso.github.io/ienumerable",
  "ieuan": "ieuan.tk",
  "iffe": "iffe-team.github.io",
  "ifis": "razod.github.io/ifis",
  "iflow": "unadlib.github.io/iflow",
  "ignite": "ignitejscl.github.io",
  "iiilfaaa": "iiilfaaa.github.io",
  "iiimix": "iiimix.github.io/iiimixjsorg",
  "iio": "iioinc.github.io/iio.js", // noCF? (don´t add this in a new PR)
  "ilfa": "iiilfaaa.github.io/www",
  "illuxi": "razod.github.io/illuxi",
  "ilzamafif": "ilzamafif.github.io",
  "imagecapture": "googlechrome.github.io/imagecapture-polyfill",
  "imask": "unmanner.github.io/imaskjs",
  "imbue": "ghosts.github.io/Imbue",
  "imcvampire": "imcvampire.github.io",
  "imeme": "svenmeister.github.io/imeme.js.org",
  "imgops": "dogancelik.github.io/imgops-multi", // noCF
  "iminfinity": "js-org-test.netlify.app",
  "immense": "immense.github.io", // noCF? (don´t add this in a new PR)
  "immybox": "immense.github.io/immybox", // noCF? (don´t add this in a new PR)
  "impress": "impress.github.io/impress.js",
  "imrc-datetime-picker": "smrsan76.github.io/imrc-datetime-picker",
  "incite": "movny.github.io/it",
  "inert": "codemaster138.github.io/inert",
  "infinite-tree": "cheton.github.io/infinite-tree",
  "infinity": "dragoonzx.github.io/infinity",
  "inig": "inig.github.io",
  "initial-wu": "initial-wu.github.io",
  "injectify": "injectify.github.io/docs",
  "inko": "inko.netlify.com",
  "inline-style-prefixer": "rofrischmann.github.io/inline-style-prefixer",
  "innova": "innova-fll.github.io",
  "inscriptum": "sumbad.github.io/inscriptum",
  "inset": "patlillis.github.io/inset.js",
  "insta": "androz2091.github.io/instajs-website",
  "instabousing": "jlbousing.github.io/instaBousing",
  "instacam": "xavierfoucrier.github.io/instacam",
  "instant": "instant.github.io",
  "integreat": "hosting.gitbook.com",
  "intelligo": "intelligo.netlify.com",
  "intertwinestaff": "0b91836f-00a9-4df3-bef4-d20310daf93d.repl.co",
  "interview": "fengzilong.github.io/interview-101",
  "invoicing": "vahe.github.io/InvoicingJs",
  "ion": "ionjs-dev.github.io",
  "iori": "iori20091101.github.io",
  "iot": "product-engineer.github.io/iot.js.org", // noCF
  "ip-address": "beaugunderson.github.io/ip-address", // noCF? (don´t add this in a new PR)
  "ipang": "ipang-dwi.github.io/ipang",
  "ipe": "wjghj-project.github.io/InPageEdit-Document",
  "ipv4": "licshee.github.io/IPv4-CIDR-Prefix-Merger",
  "ipynb": "jirutka.github.io/ipynb2html", // noCF
  "ir": "irjs.github.io/docs",
  "iresume": "supremefish.github.io/iresume",
  "iro": "jaames.github.io/iro.js",
  "irouter": "alhaqhassan.github.io/irouter.js",
  "is": "arasatasaygin.github.io/is.js", // noCF? (don´t add this in a new PR)
  "isbot": "omrilotan.github.io/isbot",
  "iscaptive": "marvnet.github.io/iscaptive",
  "isfa": "isfaaghyth.github.io",
  "ishan": "ishanthukral.github.io/ishan.js", // noCF? (don´t add this in a new PR)
  "isic": "isic.github.io/isic-docs",
  "islisp": "ta2gch.github.io/islisp.js.org",
  "istanbul": "istanbuljs.github.io",
  "italia": "italia-js.github.io",
  "itsashis4u": "itsashis4u.github.io", // noCF? (don´t add this in a new PR)
  "itunes-bridge": "angrykiller.github.io/iTunes-bridge",
  "itzik": "itzik.netlify.app",
  "iutdb": "xchairs.github.io/iutdb.github.io",
  "ivy": "sinistrecyborg.github.io/Ivy",
  "iwanttocountfromone": "realcyguy.github.io/iwanttocountfromone.js",
  "j3n5en": "j3n5en.github.io",
  "jackyef": "jackyef.github.io/jackyef",
  "jacob": "jacob-marshall.github.io/jacob",
  "jacob-ebey": "jacob-ebey.github.io",
  "jacques": "jacquesmarais.github.io/jacques", // noCF? (don´t add this in a new PR)
  "jaibascript": "vasco3.github.io/jaibascript",
  "jaipur": "jaipurjs-website-7b695.netlify.com",
  "jakarta": "jakartajs.github.io/jakartajs", // noCF? (don´t add this in a new PR)
  "jamal": "jamaljs.github.io/jamaljs",
  "james": "jamesrowen.github.io/james", // noCF? (don´t add this in a new PR)
  "jameshrx": "sawyerbx.github.io/james",
  "jargon": "hugogiraudel.github.io/SJSJ", // noCF? (don´t add this in a new PR)
  "jasonliang": "jasonliang-dev.github.io",
  "javali": "diogomoretti.github.io/javali",
  "javascript-kitchen": "jskitchen.github.io",
  "jayzou": "jayzou.github.io",
  "jbone": "kupriyanenko.github.io/jbone", // noCF? (don´t add this in a new PR)
  "jcord": "discord-jcord.github.io/jcord",
  "jdc": "jdceeb.github.io",
  "jds": "alimanman.github.io/jds",
  "jena": "javascript-in-jena.github.io", // noCF
  "jets": "nexts.github.io/Jets.js",
  "jinya": "chenjinya.github.io",
  "jjlc": "k-yak.github.io/JJLC", // noCF? (don´t add this in a new PR)
  "jk": "joname1.github.io",
  "jl": "crusj.github.io",
  "jobs": "alias.zeit.co", // noCF
  "joelmathew": "Rec0iL99.github.io/joelmathew",
  "jogja": "jogjajs.github.io", // noCF
  "john": "jozhn.github.io",
  "jokes": "jeff-tian.github.io/jokes",
  "jonathangt": "jonathangt.github.io/portafolio",
  "jonny": "shirajuki.github.io/jonny",
  "jonnynl": "shirajuki.github.io/jonnynl",
  "jomb": "mrtampan.github.io/jomb-music",
  "jonstonchan": "jonstonchan.gitlab.io", // noCF
  "jose-qs": "jose-qs.github.io/Portafolio",
  "josep": "warlock.github.io",
  "jparticles": "jparticles.github.io/Documentation",
  "js-fixerr": "anujsinghwd.github.io/js-fixerr",
  "jscord": "thepoptartcrpr.github.io/jscord",
  "jsdec": "liulihaocai.github.io/JSDec",
  "jsnippet": "JesseEisen.github.io/snippets", // noCF
  "jsoboro": "jsoboro.github.io",
  "json-e": "taskcluster.github.io/json-e",
  "json-schema-faker": "json-schema-faker.github.io/website-jsf",
  "jsonapi": "ethanresnick.github.io/json-api",
  "jsoning": "khalby786.github.io/jsoning",
  "jsonql": "joel-chu.github.io/jsonql-org",
  "jsonui": "yourtion.github.io/vue-json-ui-editor",
  "jsonuri": "aligay.github.io/jsonuri",
  "jsxcad": "jsxcad.github.io",
  "juancarlosqr": "juancarlosqr.github.io", // noCF? (don´t add this in a new PR)
  "julianflancheros": "julianflancheros.github.io/Prueba",
  "julien": "julien.github.io", // noCF? (don´t add this in a new PR)
  "juno-106": "stevengoldberg.github.io/juno-106", // noCF? (don´t add this in a new PR)
  "jus": "zeke.github.io/jus.js.org", // noCF? (don´t add this in a new PR)
  "just": "justjs.github.io",
  "justin-schroeder": "justin-schroeder.github.io",
  "juzgados": "mteyss.github.io/juzgados",
  "jwjawa": "jwjawa.github.io",
  "jwt-autorefresh": "cchamberlain.github.io/jwt-autorefresh", // noCF? (don´t add this in a new PR)
  "jwtonline": "boneyt92.github.io/jwtonline",
  "jz": "jz6.github.io",
  "kafka": "tulios.github.io/kafkajs",
  "kahoot": "na-west1.surge.sh",
  "kahoot-js": "theusaf.github.io/kahoot.js-updated",
  "kainy": "kainy.github.io/js.org",
  "kairusds": "kairusds.github.io",
  "kali": "kali65536.github.io",
  "kalm": "fed135.github.io/kalm.github.io", // noCF? (don´t add this in a new PR)
  "kanji": "eidoriantan.github.io/kanji.js",
  "karateblobs": "karatewumpus.github.io/karateblobs",
  "karl": "focused-bassi-cc0eff.netlify.com",
  "karolina-and-ryan": "mockturtlesoup.github.io/karolina-and-ryan",
  "karrot": "peyk2z90qmqzvm93.preview.edgeapp.net",
  "kasfy": "kasfy.github.io/kasfy.js.org",
  "kate": "thecodesuite.github.io/katebot",
  "katheesh": "katheesh.github.io/katheesh.js",
  "kavan": "kavanmevada.gitlab.io/intro",
  "kawaii": "moemoesoft.github.io/kawaii", // noCF
  "kcak11": "kcak11.github.io/js-org-web",
  "kdiacodes": "kdiacodes.github.io",
  "kea": "kea.netlify.app",
  "keeping-up-with-javascript": "jasperv.github.io/keeping-up-with-javascript",
  "keerthisree": "naveenjujaray.github.io/jksblog",
  "kelvinho": "kelvin2go.github.io", // noCF? (don´t add this in a new PR)
  "kewitz": "kewitz.github.io",
  "keypress": "rumkin.github.io/keypress.js.org",
  "keystone": "keystone-ssg.netlify.app",
  "kilic": "kiliczsh.github.io",
  "kilobyte": "kilobytehq.github.io/open-js",
  "kilvin": "rofrischmann.github.io/kilvin",
  "kim": "khareemnurulla.github.io/kim",
  "kindavishal": "kindavishal.netlify.com",
  "kiranremmarasu": "kiranremmarasu.github.io/kiranremmarasu",
  "kite": "kite-js.github.io/kite",
  "kiwidocs": "arguiot.github.io/KiwiDocs",
  "klasa": "dirigeants.github.io/klasa-website",
  "klasy-eris": "motiontheking.github.io/klasy-eris",
  "klepto": "mwjaworski.github.io/klepto",
  "klick": "hosting.gitbook.com",
  "kmeans": "jeff-tian.github.io/k-means",
  "knacss-vue": "arnissolle.github.io/knacss-vue",
  "knc": "chaituknag.github.io",
  "knowyourbundle": "enapupe.github.io/know-your-bundle",
  "ko": "ko25july.github.io/ko.js.org",
  "ko.redux": "deminoth.github.io/redux", // noCF
  "koa-rest-api-boilerplate": "posquit0.github.io/koa-rest-api-boilerplate",
  "kobra": "johnsylvain.github.io/kobra",
  "kodadot": "kodadot.github.io",
  "kofiloop": "norech.github.io/KofiLoop",
  "koishi": "koishijs.github.io",
  "kokoro": "cool2645.github.io/kokoro",
  "kokoro-player": "cool2645.github.io/kokoro-player",
  "komada": "dirigeants.github.io/komada",
  "komo": "jskull.github.io/komo",
  "konsumer": "konsumer.github.io", // noCF? (don´t add this in a new PR)
  "koolclash": "sukkaw.github.io/Koolshare-Clash",
  "koot": "cmux.github.io/koot",
  "koutla-swiss": "leny.github.io/koutla-swiss",
  "kovart": "kovart.github.io/cv",
  "kowalski": "k0walslk1.github.io",
  "kra": "kra-framework.github.io/kra-suite", // noCF
  "kremling": "canopytax.github.io/kremling.js.org",
  "kreta-api-v3": "daaniiieel.github.io/kreta-api-v3",
  "kreta-cli": "daaniiieel.github.io/kreta-cli",
  "kshitij": "kshitij98.github.io",
  "ksp": "keepsobp.github.io",
  "kst": "lucaelin.github.io/KST", // noCF
  "ktm": "developers-nepal.github.io/ktmjs",
  "kucos": "kucosjs.github.io",
  "kunal": "kunalghosh02.github.io",
  "kunkun": "smallkunkun.github.io",
  "kyoto": "kyotojs.github.io",
  "l2dwidget": "xiazeyu.github.io/live2d-widget.js-doc",
  "lab": "labjs.netlify.com",
  "labelauty": "fntneves.github.io/jquery-labelauty", // noCF? (don´t add this in a new PR)
  "lad": "ladjs.github.io/lad",
  "lambda": "lambdajs.github.io", // noCF? (don´t add this in a new PR)
  "lance": "lancepioch.com",
  "landrielportafolio": "arielandriel30.github.io/landrielportafolio",
  "languages": "rsamaium.github.io/Languages",
  "larastrator": "the94air.github.io/larastrator",
  "lasers": "lukehorvat.github.io/need-more-lasers",
  "lass": "lassjs.github.io/lass",
  "latex": "michael-brade.github.io/LaTeX.js",
  "latte": "tehsenaus.github.io/latte-js",
  "laubstein": "laubstein.github.io", // noCF? (don´t add this in a new PR)
  "laue": "qingwei-li.github.io/laue",
  "lava": "palladium.github.io/Lava.js",
  "lavaclient": "lavaclient.github.io",
  "laveesh": "laveesh.github.io",
  "lazycipher": "lazycipher.github.io",
  "lcookie": "lf112.github.io/lcookie",
  "ldf": "autplayed.github.io/ldf",
  "le": "letui.github.io",
  "leafless": "mofax.github.io/leafless",
  "lean-stack": "lean-stack.github.io", // noCF? (don´t add this in a new PR)
  "leandro": "leandrowd.github.io", // noCF? (don´t add this in a new PR)
  "learnathon": "learn-a-thon.netlify.com",
  "learngitbranching": "pcottle.github.io/learnGitBranching",
  "learningenglish": "guilhermedelemos.github.io/Learning-English",
  "lecashbot": "thetypingmatch.github.io/lecashbot-docs",
  "lee": "lee981265.github.io",
  "leeks": "ohlookitsderpy.github.io/leeks.js",
  "leet": "leetcodes.github.io",
  "lego": "polight.github.io/lego",
  "leipzig": "leipzigjs.github.io", // noCF? (don´t add this in a new PR)
  "lemn": "lemnjs.github.io/lemn",
  "leo": "leo66123.github.io",
  "leoj": "leoaj.github.io", // noCF? (don´t add this in a new PR)
  "lerna": "lerna.github.io/website",
  "lessmd": "linuxenko.github.io/lessmd",
  "leste": "atwood-cai.github.io/leste.js", // noCF? (don´t add this in a new PR)
  "lete": "cname.vercel-dns.com",
  "level": "xv700.github.io/level",
  "lf": "lf112.github.io",
  "lgs": "lgsturkiye.github.io/lgs",
  "li": "mattsimmons1.github.io/li",
  "libphonenumbers": "libphonenumbers.github.io",
  "lifeisyoung": "lifeisyoung.github.io",
  "lifx": "fncxpro.github.io/lifx.js",
  "light": "lightjs.netlify.com",
  "light-observable": "dmitry-korolev.github.io/light-observable",
  "lightimage": "jwchan1996.github.io/lightimage.js",
  "liguori": "liguori.github.io", // noCF? (don´t add this in a new PR)
  "liike": "liikejs.github.io/Liike",
  "likebeta": "likebeta.github.io/likebeta.js.org",
  "liljs": "liljs.netlify.com",
  "lillie": "lillie.shii.ro",
  "lim": "lim.netlify.app",
  "limitrr": "eddiejibson.github.io/limitrr",
  "lineup": "lineupjs.github.io",
  "lineupengine": "lineupjs.github.io/lineupengine.js.org",
  "ling": "wangziling.github.io",
  "linghucong": "jiji262.github.io",
  "lingui": "cname.vercel-dns.com",
  "lister": "jpbulman.github.io/lister",
  "litedom": "mardix.github.io/litedom", // noCF
  "liudun": "haveataste.github.io/liudun",
  "liuence": "lxyzai.github.io/liuence",
  "liusai": "webwuyou.github.io",
  "live-editor": "geard-dev.github.io/web-based-live-code-editor",
  "liveflow": "hasharray.github.io/liveflow.js",
  "livenotif": "siffreinsg.github.io/livenotif",
  "lmajercik": "meiercheek.github.io",
  "lmk": "limengke123.github.io/newBlog",
  "localsync": "noderaider.github.io/localsync", // noCF? (don´t add this in a new PR)
  "loginlock-portfolio": "chucky22mendoza.github.io/loginlock",
  "logo": "js-org.github.io/logo",
  "loki": "oblador.github.io/loki",
  "lol": "xcss.github.io/lol",
  "loli": "tkzcm.github.io/loli",
  "lombok": "lombokjs.github.io",
  "loog": "israelroldan.github.io/loog",
  "lostyle": "rtsao.github.io/lostyle",
  "lottiefy": "pd4d10.github.io/lottiefy",
  "lps": "mauris.github.io/lps.js.org",
  "lribeiro": "lmribeiro.github.io",
  "ls": "links-js.github.io",
  "lucia": "lucia.netlify.app",
  "lucy": "lucy-bot.github.io",
  "luis": "luiscloud.github.io",
  "lukks": "lukks.github.io/page",
  "luzc": "lucianing.github.io/notes",
  "lvp": "luzhenqian.github.io/lvp.js",
  "lwd-db": "dreamingbot.github.io/Login-With-Discord-DB",
  "lwjerri": "lwjerri.github.io",
  "lx": "blleng.github.io/lx",
  "lychee": "Artificial-Engineering.github.io/lycheeJS-website",
  "lyertia": "lyertia.github.io",
  "lyra": "amansahil.github.io/lyra.js.org",
  "lzbible": "edwinyosorahardjo.github.io/lzbible",
  "m01i0ng": "m01i0ng.github.io",
  "m8bot": "mapreiff.github.io/m8-bot-site",
  "ma124": "ma124.netlify.com",
  "machinelearning": "marink.github.io/machinelearning",
  "macosnotif": "mattipv4.github.io/macOSNotifJS",
  "madankumar": "jmadankumar.github.io",
  "madebyzen": "mzaini30.github.io/madebyzen",
  "magnet": "magnetjs.github.io/Magnet", // noCF? (don´t add this in a new PR)
  "mahdyar": "mahdyar.github.io/mahdyar.js.org",
  "mahmoud": "mahmoud-sagharjoughi.github.io/mahmoud",
  "mailgo": "mailgo.netlify.com", // noCF
  "mainframebot": "mainframebot.github.io",
  "majestic": "moityjs.github.io/majestic",
  "maker": "microsoft.github.io/maker.js",
  "makes": "makesjs.github.io",
  "mali": "malijs.github.io",
  "manic": "manicjs.github.io",
  "mansiart": "mansiart.github.io/mansiart",
  "manu": "botsdemanu.github.io/manu",
  "manual.bluelightos": "hosting.gitbook.com",
  "manytimepad": "dipanshkhandelwal.github.io/ManyTimePad",
  "mapa-cultura": "opensas.gitlab.io",
  "mappa": "cvalenzuela.github.io/Mappa",
  "marble": "jsguy.github.io/marble",
  "marcelo": "marcelooggero.github.io/bootstrap",
  "marie": "marie-js.github.io/MARIE.js",
  "mark": "henry-luo.github.io/mark",
  "markbox": "markbox.netlify.com",
  "markdown-notepad": "jz222.github.io/markdown-notepad",
  "markdownify": "amitmerchant1990.github.io/electron-markdownify",
  "marked": "cname.vercel-dns.com", // noCF
  "markmap": "gera2ld.github.io/markmap-lib",
  "markmsmith": "markmsmith.github.io",
  "markvis": "geekplux.github.io/markvis",
  "markvis-editor": "geekplux.github.io/markvis-editor",
  "mars": "marswong.github.io/blog",
  "martin": "martinbutler.github.io", // noCF? (don´t add this in a new PR)
  "martingollogly": "martingollogly.github.io", // noCF? (don´t add this in a new PR)
  "marxist": "wuz.github.io/marxistjs",
  "masha": "smarttelemax.github.io/MaSha",
  "master-portfolio": "vimalverma558.github.io/Master-Portfolio",
  "mateocontenla": "taconeomental.github.io/mateocontenla",
  "materialish": "jamesplease.github.io/materialish",
  "materialize-bootbox": "iqbalfn.github.io/materialize-bootbox",
  "math": "hegartycalculator.github.io/math.js",
  "matrix-rref-solver": "arisweedler.github.io/matrix-rref-solver",
  "matters2ipfs": "contributionls.github.io/matters2ipfs",
  "matthias-schuetz": "matthias-schuetz.github.io", // noCF? (don´t add this in a new PR)
  "mauricio": "mauricionobrega.github.io/www",
  "max": "toorusr.github.io/max.js.org",
  "maxnachlinger": "maxnachlinger.github.io", // noCF? (don´t add this in a new PR)
  "maxtracking": "maxtracking.github.io", // noCF? (don´t add this in a new PR)
  "mc": "magicarbon.github.io/mc", // noCF? (don´t add this in a new PR)
  "mcul": "teamtofu.github.io/mcul",
  "mdbf-css": "more-beautiful-div-framework.github.io",
  "mde": "lukehorvat.github.io/mde-soundboard",
  "mechan": "dusterthefirst.github.io/mechan.js",
  "medan": "medan-js.github.io", // noCF
  "media": "tobiasthaden.github.io/media.js",
  "media-style-palette": "rikakomoe.github.io/Media-Style-Palette",
  "mediainfo": "buzz.github.io/mediainfo.js",
  "medit": "echosoar.github.io/medit",
  "medium-converter": "gunar.github.io/medium-converter", // noCF
  "meed": "pinjasaur.github.io/meed",
  "megacode18": "megacode18.github.io",
  "meiosis": "foxdonut.github.io/meiosis", // noCF? (don´t add this in a new PR)
  "melies-hugo": "cristinafsanz.github.io/melies-hugo",
  "melody": "trivago.github.io/melody-web",
  "memento": "jeanfortheweb.gitbooks.io/memento",
  "menghafalquran": "mzaini30.github.io/menghafal-quran",
  "mercury": "henryqw.github.io/mercury",
  "merkletree": "miguelmota.github.io/merkletreejs",
  "merkur": "mjancarik.github.io/merkur",
  "mern": "IamMohaiminul.GitHub.io/MERNjs",
  "mert": "mert574.github.io",
  "mesh": "crcn.github.io/mesh.js.org", // noCF? (don´t add this in a new PR)
  "meshesha": "meshesha.github.io",
  "metadata": "oknosoft.github.io/metadata.js",
  "metascraper": "microlinkhq.github.io/metascraper",
  "meth": "meth-meth-method.github.io/meth",
  "metools": "yimogit.github.io/metools-plugin",
  "meyda": "meyda.github.io",
  "mf": "awto.github.io/mfjs-compiler", // noCF? (don´t add this in a new PR)
  "mhsupport": "thatonetqnk.github.io/MHSupport",
  "mhy": "hosting.gitbook.com", // noCF
  "mi": "stevenjoezhang.github.io",
  "michaelfarnik": "michaloslav.github.io/MichaelFarnik",
  "microfeedback": "microfeedback.github.io",
  "microlink": "microlinkhq.github.io/microlinkjs",
  "mics": "download.github.io/mics",
  "middy": "plnt9.github.io/middy",
  "miguelsr": "miguelsr.github.io", // noCF? (don´t add this in a new PR)
  "mikado": "nextapps-de.github.io/mikado",
  "milesgitgud": "milesgitgud.github.io/homepage",
  "militia": "militia21.github.io/militia",
  "militia21": "militia21.github.io/militia21",
  "m
