name: Comment

on:
  workflow_run:
    workflows:
      - Validate
    types:
      - completed

permissions: {}

jobs:
  comment:
    # Only leave comments on PRs, except when the PR is from Dependabot
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].user.login != 'dependabot[bot]'

    name: PR comment
    runs-on: ubuntu-latest

    permissions:
      actions: read
      checks: read
      pull-requests: write

    steps:
      - name: Generate message
        id: message
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const workflowRun = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });

            const checks = await github.rest.checks.listForSuite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_suite_id: workflowRun.data.check_suite_id,
            });

            const cnamesCheck = checks.data.check_runs.find(check => check.name === "cnames_active.js");
            if (!cnamesCheck) throw new Error("Could not find cnames_active.js check run");

            const descriptionCheck = checks.data.check_runs.find(check => check.name === "PR description");
            if (!descriptionCheck) throw new Error("Could not find PR description check run");
            
            const messages = [];
            
            // 1. cnames_active.js validation result, linking to the files changed tab for annotations
            if (cnamesCheck.conclusion === 'failure') {
              messages.push(
                "**❌ `cnames_active.js` validation failed due to being incorrectly formatted.**",
                `_[Check file annotations for failure details](${context.payload.workflow_run.pull_requests[0].html_url}/files)._`,
                "", "---", "",
              );
            }

            // 2. PR description validation result, linking to the raw PR template file for reference
            if (descriptionCheck.conclusion === 'failure') {
              const descriptionAnnotations = await github.rest.checks.listAnnotations({
                owner: context.repo.owner,
                repo: context.repo.repo,
                check_run_id: descriptionCheck.id,
              });
              if (!descriptionAnnotations.data[0]) throw new Error("Could not find annotations for PR description check run");

              messages.push(
                "**❌ PR description validation failed due to being incorrectly formatted.**",
                `_[Use the provided template and ensure all information is provided](https://raw.githubusercontent.com/${context.repo.owner}/${context.repo.repo}/${context.payload.repository.default_branch}/PULL_REQUEST_TEMPLATE.md)._`,
                "",
                descriptionAnnotations.data[0].message.split("\n").slice(1).join("\n"),
                "", "---", "",
              );
            }

            if (messages.length) {
              messages.push("**⚠️ You must resolve these issues before your JS.org subdomain request can be accepted.**");
              core.setOutput("message", messages.join("\n"));
            } else {
              core.setOutput("message", "✅ All validations passed! Please wait for the JS.org maintainers to process your subdomain request.");
            }

      - name: Post comment
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          message: ${{ steps.message.outputs.message }}
          comment-tag: jsorg-validation
          pr-number: ${{ github.event.workflow_run.pull_requests[0].number }}
